import type { Vocabulary } from "@/lib/vocab-types";

/** Động vật & trái cây — sinh từ scripts/*-catalog.js (node scripts/generate-animals-vocs.js) */
export const animalsLearningVocs: Vocabulary[] = [
  {
    id: "LEARN_ANIMAL_01",
    voc: "horse",
    pos: "n",
    meaning: "con ngựa",
    ipa: "/hɔːs/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/horse.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_02",
    voc: "sheep",
    pos: "n",
    meaning: "con cừu",
    ipa: "/ʃiːp/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/sheep.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_03",
    voc: "rabbit",
    pos: "n",
    meaning: "con thỏ",
    ipa: "/ˈræbɪt/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/rabbit.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_04",
    voc: "frog",
    pos: "n",
    meaning: "con ếch",
    ipa: "/frɒɡ/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/frog.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_05",
    voc: "bee",
    pos: "n",
    meaning: "con ong",
    ipa: "/biː/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/bee.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_06",
    voc: "deer",
    pos: "n",
    meaning: "con hươu",
    ipa: "/dɪə/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/deer.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_07",
    voc: "goat",
    pos: "n",
    meaning: "con dê",
    ipa: "/ɡəʊt/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/goat.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_08",
    voc: "squirrel",
    pos: "n",
    meaning: "con sóc",
    ipa: "/ˈskwɪrəl/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/squirrel.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_09",
    voc: "turtle",
    pos: "n",
    meaning: "con rùa",
    ipa: "/ˈtɜːtl/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/turtle.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_10",
    voc: "owl",
    pos: "n",
    meaning: "con cú",
    ipa: "/aʊl/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/owl.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_11",
    voc: "fox",
    pos: "n",
    meaning: "con cáo",
    ipa: "/fɒks/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/fox.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_12",
    voc: "wolf",
    pos: "n",
    meaning: "con sói",
    ipa: "/wʊlf/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/wolf.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_13",
    voc: "mouse",
    pos: "n",
    meaning: "con chuột",
    ipa: "/maʊs/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/mouse.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_14",
    voc: "monkey",
    pos: "n",
    meaning: "con khỉ",
    ipa: "/ˈmʌŋki/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/monkey.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_15",
    voc: "snake",
    pos: "n",
    meaning: "con rắn",
    ipa: "/sneɪk/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/snake.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_16",
    voc: "butterfly",
    pos: "n",
    meaning: "con bướm",
    ipa: "/ˈbʌtəflaɪ/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/butterfly.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_17",
    voc: "bear",
    pos: "n",
    meaning: "con gấu",
    ipa: "/beə/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/bear.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_18",
    voc: "lion",
    pos: "n",
    meaning: "sư tử",
    ipa: "/ˈlaɪən/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/lion.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_19",
    voc: "tiger",
    pos: "n",
    meaning: "con hổ",
    ipa: "/ˈtaɪɡə/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/tiger.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_20",
    voc: "elephant",
    pos: "n",
    meaning: "con voi",
    ipa: "/ˈelɪfənt/",
    category: "Animals",
    setGroup: "basic",
    image: require("./data/animals/elephant.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_21",
    voc: "giraffe",
    pos: "n",
    meaning: "hươu cao cổ",
    ipa: "/dʒɪˈrɑːf/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/giraffe.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_22",
    voc: "zebra",
    pos: "n",
    meaning: "ngựa vằn",
    ipa: "/ˈzebrə/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/zebra.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_23",
    voc: "penguin",
    pos: "n",
    meaning: "chim cánh cụt",
    ipa: "/ˈpeŋɡwɪn/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/penguin.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_24",
    voc: "dolphin",
    pos: "n",
    meaning: "cá heo",
    ipa: "/ˈdɒlfɪn/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/dolphin.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_25",
    voc: "whale",
    pos: "n",
    meaning: "cá voi",
    ipa: "/weɪl/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/whale.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_26",
    voc: "shark",
    pos: "n",
    meaning: "cá mập",
    ipa: "/ʃɑːk/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/shark.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_27",
    voc: "eagle",
    pos: "n",
    meaning: "chim đại bàng",
    ipa: "/ˈiːɡl/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/eagle.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_28",
    voc: "kangaroo",
    pos: "n",
    meaning: "chuột túi",
    ipa: "/ˌkæŋɡəˈruː/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/kangaroo.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_29",
    voc: "crocodile",
    pos: "n",
    meaning: "cá sấu",
    ipa: "/ˈkrɒkədaɪl/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/crocodile.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_30",
    voc: "hippopotamus",
    pos: "n",
    meaning: "hà mã",
    ipa: "/ˌhɪpəˈpɒtəməs/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/hippopotamus.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_31",
    voc: "rhinoceros",
    pos: "n",
    meaning: "tê giác",
    ipa: "/raɪˈnɒsərəs/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/rhinoceros.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_32",
    voc: "camel",
    pos: "n",
    meaning: "con lạc đà",
    ipa: "/ˈkæml/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/camel.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_33",
    voc: "leopard",
    pos: "n",
    meaning: "báo đốm",
    ipa: "/ˈlepəd/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/leopard.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_34",
    voc: "cheetah",
    pos: "n",
    meaning: "báo săn",
    ipa: "/ˈtʃiːtə/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/cheetah.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_35",
    voc: "octopus",
    pos: "n",
    meaning: "bạch tuộc",
    ipa: "/ˈɒktəpəs/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/octopus.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_36",
    voc: "flamingo",
    pos: "n",
    meaning: "hồng hạc",
    ipa: "/fləˈmɪŋɡəʊ/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/flamingo.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_37",
    voc: "peacock",
    pos: "n",
    meaning: "con công",
    ipa: "/ˈpiːkɒk/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/peacock.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_38",
    voc: "chameleon",
    pos: "n",
    meaning: "tắc kè hoa",
    ipa: "/kəˈmiːliən/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/chameleon.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_39",
    voc: "porcupine",
    pos: "n",
    meaning: "nhím",
    ipa: "/ˈpɔːkjupaɪn/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/porcupine.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_40",
    voc: "bat",
    pos: "n",
    meaning: "con dơi",
    ipa: "/bæt/",
    category: "Animals",
    setGroup: "wild",
    image: require("./data/animals/bat.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_41",
    voc: "gorilla",
    pos: "n",
    meaning: "tinh tinh",
    ipa: "/ɡəˈrɪlə/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/gorilla.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_42",
    voc: "orangutan",
    pos: "n",
    meaning: "đười ươi",
    ipa: "/əˈræŋʊtæn/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/orangutan.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_43",
    voc: "walrus",
    pos: "n",
    meaning: "hải mã",
    ipa: "/ˈwɔːl.rəs/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/walrus.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_44",
    voc: "seal",
    pos: "n",
    meaning: "hải cẩu",
    ipa: "/siːl/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/seal.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_45",
    voc: "otter",
    pos: "n",
    meaning: "rái cá",
    ipa: "/ˈɒtə/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/otter.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_46",
    voc: "beaver",
    pos: "n",
    meaning: "hải ly",
    ipa: "/ˈbiːvə/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/beaver.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_47",
    voc: "raccoon",
    pos: "n",
    meaning: "gấu mèo",
    ipa: "/rəˈkuːn/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/raccoon.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_48",
    voc: "hedgehog",
    pos: "n",
    meaning: "nhím gai",
    ipa: "/ˈhedʒhɒɡ/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/hedgehog.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_49",
    voc: "armadillo",
    pos: "n",
    meaning: "tê tấc",
    ipa: "/ˌɑːməˈdɪləʊ/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/armadillo.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_50",
    voc: "platypus",
    pos: "n",
    meaning: "thú mỏ vịt",
    ipa: "/ˈplætɪpəs/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/platypus.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_51",
    voc: "antelope",
    pos: "n",
    meaning: "linh dương",
    ipa: "/ˈæntɪləʊp/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/antelope.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_52",
    voc: "bison",
    pos: "n",
    meaning: "trâu bison",
    ipa: "/ˈbaɪsən/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/bison.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_53",
    voc: "moose",
    pos: "n",
    meaning: "nai sừng xẻ",
    ipa: "/muːs/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/moose.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_54",
    voc: "pelican",
    pos: "n",
    meaning: "bồ nông",
    ipa: "/ˈpelɪkən/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/pelican.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_55",
    voc: "toucan",
    pos: "n",
    meaning: "chim toucan",
    ipa: "/ˈtuːkæn/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/toucan.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_56",
    voc: "scorpion",
    pos: "n",
    meaning: "bọ cạp",
    ipa: "/ˈskɔːpiən/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/scorpion.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_57",
    voc: "jellyfish",
    pos: "n",
    meaning: "sứa",
    ipa: "/ˈdʒelifɪʃ/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/jellyfish.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_58",
    voc: "starfish",
    pos: "n",
    meaning: "sao biển",
    ipa: "/ˈstɑːfɪʃ/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/starfish.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_59",
    voc: "seahorse",
    pos: "n",
    meaning: "cá ngựa",
    ipa: "/ˈsiːhɔːs/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/seahorse.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_60",
    voc: "lobster",
    pos: "n",
    meaning: "tôm hùm",
    ipa: "/ˈlɒbstə/",
    category: "Animals",
    setGroup: "advanced",
    image: require("./data/animals/lobster.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_61",
    voc: "alligator",
    pos: "n",
    meaning: "cá sấu Mỹ",
    ipa: "/ˈælɪɡeɪtə/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/alligator.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_62",
    voc: "komodo dragon",
    pos: "n",
    meaning: "rồng Komodo",
    ipa: "/kəˈməʊdəʊ ˈdræɡən/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/komodo-dragon.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_63",
    voc: "narwhal",
    pos: "n",
    meaning: "kỳ lân biển",
    ipa: "/ˈnɑːwəl/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/narwhal.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_64",
    voc: "manatee",
    pos: "n",
    meaning: "lợn biển",
    ipa: "/ˌmænəˈtiː/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/manatee.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_65",
    voc: "pangolin",
    pos: "n",
    meaning: "tê tẽ",
    ipa: "/ˈpæŋɡəlɪn/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/pangolin.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_66",
    voc: "axolotl",
    pos: "n",
    meaning: "kỳ giông Mexico",
    ipa: "/ˈæksəlɒtəl/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/axolotl.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_67",
    voc: "ferret",
    pos: "n",
    meaning: "chồn",
    ipa: "/ˈferɪt/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/ferret.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_68",
    voc: "meerkat",
    pos: "n",
    meaning: "cầy vằn",
    ipa: "/ˈmɪəkæt/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/meerkat.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_69",
    voc: "sloth",
    pos: "n",
    meaning: "lười",
    ipa: "/sləʊθ/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/sloth.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_70",
    voc: "anteater",
    pos: "n",
    meaning: "kiến ăn",
    ipa: "/ˈænt.iːtə/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/anteater.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_71",
    voc: "hyena",
    pos: "n",
    meaning: "linh cẩu",
    ipa: "/haɪˈiːnə/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/hyena.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_72",
    voc: "vulture",
    pos: "n",
    meaning: "kền kền",
    ipa: "/ˈvʌltʃə/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/vulture.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_73",
    voc: "ostrich",
    pos: "n",
    meaning: "đà điểu",
    ipa: "/ˈɒstrɪtʃ/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/ostrich.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_74",
    voc: "emu",
    pos: "n",
    meaning: "đà điểu Úc",
    ipa: "/ˈiːmjuː/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/emu.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_75",
    voc: "koala",
    pos: "n",
    meaning: "koala",
    ipa: "/kəʊˈɑːlə/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/koala.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_76",
    voc: "panda",
    pos: "n",
    meaning: "gấu trúc",
    ipa: "/ˈpændə/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/panda.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_77",
    voc: "lynx",
    pos: "n",
    meaning: "linh miêu",
    ipa: "/lɪŋks/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/lynx.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_78",
    voc: "badger",
    pos: "n",
    meaning: "lửng",
    ipa: "/ˈbædʒə/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/badger.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_79",
    voc: "mantis",
    pos: "n",
    meaning: "bọ ngựa",
    ipa: "/ˈmæntɪs/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/mantis.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_ANIMAL_80",
    voc: "centipede",
    pos: "n",
    meaning: "rết",
    ipa: "/ˈsentɪpiːd/",
    category: "Animals",
    setGroup: "expert",
    image: require("./data/animals/centipede.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_01",
    voc: "apple",
    pos: "n",
    meaning: "quả táo",
    ipa: "/ˈæpl/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/apple.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_02",
    voc: "banana",
    pos: "n",
    meaning: "quả chuối",
    ipa: "/bəˈnɑːnə/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/banana.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_03",
    voc: "orange",
    pos: "n",
    meaning: "quả cam",
    ipa: "/ˈɒrɪndʒ/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/orange.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_04",
    voc: "grape",
    pos: "n",
    meaning: "quả nho",
    ipa: "/ɡreɪp/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/grape.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_05",
    voc: "mango",
    pos: "n",
    meaning: "quả xoài",
    ipa: "/ˈmæŋɡəʊ/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/mango.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_06",
    voc: "pineapple",
    pos: "n",
    meaning: "quả dứa",
    ipa: "/ˈpaɪnæpl/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/pineapple.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_07",
    voc: "watermelon",
    pos: "n",
    meaning: "dưa hấu",
    ipa: "/ˈwɔːtəmelən/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/watermelon.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_08",
    voc: "strawberry",
    pos: "n",
    meaning: "dâu tây",
    ipa: "/ˈstrɔːbəri/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/strawberry.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_09",
    voc: "lemon",
    pos: "n",
    meaning: "quả chanh vàng",
    ipa: "/ˈlemən/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/lemon.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_10",
    voc: "peach",
    pos: "n",
    meaning: "quả đào",
    ipa: "/piːtʃ/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/peach.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_11",
    voc: "pear",
    pos: "n",
    meaning: "quả lê",
    ipa: "/peə/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/pear.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_12",
    voc: "cherry",
    pos: "n",
    meaning: "quả cherry",
    ipa: "/ˈtʃeri/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/cherry.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_13",
    voc: "coconut",
    pos: "n",
    meaning: "quả dừa",
    ipa: "/ˈkəʊkənʌt/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/coconut.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_14",
    voc: "avocado",
    pos: "n",
    meaning: "quả bơ",
    ipa: "/ˌævəˈkɑːdəʊ/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/avocado.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_15",
    voc: "kiwi",
    pos: "n",
    meaning: "quả kiwi",
    ipa: "/ˈkiːwiː/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/kiwi.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_16",
    voc: "papaya",
    pos: "n",
    meaning: "quả đu đủ",
    ipa: "/pəˈpaɪə/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/papaya.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_17",
    voc: "melon",
    pos: "n",
    meaning: "dưa gang",
    ipa: "/ˈmelən/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/melon.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_18",
    voc: "plum",
    pos: "n",
    meaning: "quả mận",
    ipa: "/plʌm/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/plum.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_19",
    voc: "apricot",
    pos: "n",
    meaning: "quả mơ",
    ipa: "/ˈeɪprɪkɒt/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/apricot.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_20",
    voc: "pomegranate",
    pos: "n",
    meaning: "quả lựu",
    ipa: "/ˈpɒmɪɡrænɪt/",
    category: "Animals",
    setGroup: "fruit",
    image: require("./data/fruits/pomegranate.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_21",
    voc: "dragon fruit",
    pos: "n",
    meaning: "thanh long",
    ipa: "/ˈdræɡən fruːt/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/dragon-fruit.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_22",
    voc: "lychee",
    pos: "n",
    meaning: "quả vải",
    ipa: "/ˈlaɪtʃiː/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/lychee.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_23",
    voc: "durian",
    pos: "n",
    meaning: "sầu riêng",
    ipa: "/ˈdʊəriən/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/durian.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_24",
    voc: "rambutan",
    pos: "n",
    meaning: "chôm chôm",
    ipa: "/ræmˈbuːtən/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/rambutan.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_25",
    voc: "jackfruit",
    pos: "n",
    meaning: "quả mít",
    ipa: "/ˈdʒækfruːt/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/jackfruit.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_26",
    voc: "guava",
    pos: "n",
    meaning: "quả ổi",
    ipa: "/ˈɡwɑːvə/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/guava.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_27",
    voc: "passion fruit",
    pos: "n",
    meaning: "chanh dây",
    ipa: "/ˈpæʃən fruːt/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/passion-fruit.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_28",
    voc: "blueberry",
    pos: "n",
    meaning: "việt quất",
    ipa: "/ˈbluːbəri/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/blueberry.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_29",
    voc: "raspberry",
    pos: "n",
    meaning: "mâm xôi",
    ipa: "/ˈrɑːzbəri/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/raspberry.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_30",
    voc: "blackberry",
    pos: "n",
    meaning: "dâu đen",
    ipa: "/ˈblækbəri/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/blackberry.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_31",
    voc: "cranberry",
    pos: "n",
    meaning: "nam việt quất",
    ipa: "/ˈkrænbəri/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/cranberry.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_32",
    voc: "fig",
    pos: "n",
    meaning: "quả sung",
    ipa: "/fɪɡ/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/fig.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_33",
    voc: "tangerine",
    pos: "n",
    meaning: "quýt",
    ipa: "/ˌtændʒəˈriːn/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/tangerine.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_34",
    voc: "grapefruit",
    pos: "n",
    meaning: "bưởi chua",
    ipa: "/ˈɡreɪpfruːt/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/grapefruit.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_35",
    voc: "lime",
    pos: "n",
    meaning: "chanh xanh",
    ipa: "/laɪm/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/lime.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_36",
    voc: "persimmon",
    pos: "n",
    meaning: "quả hồng",
    ipa: "/pəˈsɪmən/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/persimmon.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_37",
    voc: "star fruit",
    pos: "n",
    meaning: "quả khế",
    ipa: "/ˈstɑː fruːt/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/starfruit.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_38",
    voc: "cantaloupe",
    pos: "n",
    meaning: "dưa cam",
    ipa: "/ˈkæntəluːp/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/cantaloupe.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_39",
    voc: "mangosteen",
    pos: "n",
    meaning: "măng cụt",
    ipa: "/ˈmæŋɡəstiːn/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/mangosteen.jpg"),
    useDeviceTts: true,
  },
  {
    id: "LEARN_FRUIT_40",
    voc: "date",
    pos: "n",
    meaning: "quả chà là",
    ipa: "/deɪt/",
    category: "Animals",
    setGroup: "fruit-exotic",
    image: require("./data/fruits/date.jpg"),
    useDeviceTts: true,
  },
];
