export type Vocabulary = {
  voc: string;
  meaning: string;
  sound: any;
  image: any;
};

export const new_vocs: Vocabulary[] = [
  {
    voc: "anxious",
    meaning: "lo âu, băn khoăn",
    image: require("./data/4000B2_601.jpg"),
    sound: require("./data/4000B2_anxious.mp3"),
  },
  {
    voc: "awful",
    meaning: "xấu xa, tồi tệ",
    image: require("./data/4000B2_602.jpg"),
    sound: require("./data/4000B2_awful.mp3"),
  },
  {
    voc: "consist",
    meaning: "gồm có",
    image: require("./data/4000B2_603.jpg"),
    sound: require("./data/4000B2_consist.mp3"),
  },
  {
    voc: "desire",
    meaning: "thèm muốn, ao ước",
    image: require("./data/4000B2_604.jpg"),
    sound: require("./data/4000B2_desire.mp3"),
  },
  {
    voc: "eager",
    meaning: "háo hức, hăm hở",
    image: require("./data/4000B2_605.jpg"),
    sound: require("./data/4000B2_eager.mp3"),
  },
  {
    voc: "household",
    meaning: "gia đình",
    image: require("./data/4000B2_606.jpg"),
    sound: require("./data/4000B2_household.mp3"),
  },
  {
    voc: "intent",
    meaning: "ý định, mục đích",
    image: require("./data/4000B2_607.jpg"),
    sound: require("./data/4000B2_intent.mp3"),
  },
  {
    voc: "landscape",
    meaning: "phong cảnh",
    image: require("./data/4000B2_608.jpg"),
    sound: require("./data/4000B2_landscape.mp3"),
  },
  {
    voc: "lift",
    meaning: "nâng, nhấc",
    image: require("./data/4000B2_609.jpg"),
    sound: require("./data/4000B2_lift.mp3"),
  },
  {
    voc: "load",
    meaning: "bốc hàng, chất tải, chở, nạp",
    image: require("./data/4000B2_610.jpg"),
    sound: require("./data/4000B2_load.mp3"),
  },
  {
    voc: "lung",
    meaning: "phổi",
    image: require("./data/4000B2_611.jpg"),
    sound: require("./data/4000B2_lung.mp3"),
  },
  {
    voc: "motion",
    meaning: "sự chuyển động",
    image: require("./data/4000B2_612.jpg"),
    sound: require("./data/4000B2_motion.mp3"),
  },
  {
    voc: "pace",
    meaning: "tốc độ đi, tốc độ chạy",
    image: require("./data/4000B2_613.jpg"),
    sound: require("./data/4000B2_pace.mp3"),
  },
  {
    voc: "polite",
    meaning: "lịch sự, lịch thiệp, lễ độ",
    image: require("./data/4000B2_614.jpg"),
    sound: require("./data/4000B2_polite.mp3"),
  },
  {
    voc: "possess",
    meaning: "chiếm hữu, có, sở hữu",
    image: require("./data/4000B2_615.jpg"),
    sound: require("./data/4000B2_possess.mp3"),
  },
  {
    voc: "rapidly",
    meaning: "nhanh chóng, mau lẹ",
    image: require("./data/4000B2_616.jpg"),
    sound: require("./data/4000B2_rapidly.mp3"),
  },
  {
    voc: "remark",
    meaning: "nhận xét, chú ý, lưu ý",
    image: require("./data/4000B2_617.jpg"),
    sound: require("./data/4000B2_remark.mp3"),
  },
  {
    voc: "seek",
    meaning: "đi tìm, tìm kiếm, tìm",
    image: require("./data/4000B2_618.jpg"),
    sound: require("./data/4000B2_seek.mp3"),
  },
  {
    voc: "shine",
    meaning: "toả sáng, chiếu sáng",
    image: require("./data/4000B2_619.jpg"),
    sound: require("./data/4000B2_shine.mp3"),
  },
  {
    voc: "spill",
    meaning: "đổ, trút, làm đổ",
    image: require("./data/4000B2_620.jpg"),
    sound: require("./data/4000B2_spill.mp3"),
  },
  {
    voc: "bring",
    meaning: "cầm lại, đem lại, mang lại",
    image: require("./data/4000B2_621.jpg"),
    sound: require("./data/4000B2_bring.mp3"),
  },
  {
    voc: "castle",
    meaning: "lâu đài",
    image: require("./data/4000B2_622.jpg"),
    sound: require("./data/4000B2_castle.mp3"),
  },
  {
    voc: "command",
    meaning: "ra lệnh, mệnh lệnh",
    image: require("./data/4000B2_623.jpg"),
    sound: require("./data/4000B2_command.mp3"),
  },
  {
    voc: "counsel",
    meaning: "khuyên răn, khuyên bảo, chỉ bảo",
    image: require("./data/4000B2_624.jpg"),
    sound: require("./data/4000B2_counsel.mp3"),
  },
  {
    voc: "ensure",
    meaning: "bảo đảm, chắc chắn",
    image: require("./data/4000B2_625.jpg"),
    sound: require("./data/4000B2_ensure.mp3"),
  },
  {
    voc: "explosion",
    meaning: "sự nổ, tiếng nổ",
    image: require("./data/4000B2_626.jpg"),
    sound: require("./data/4000B2_explosion.mp3"),
  },
  {
    voc: "jewelry",
    meaning: "đồ châu báu; đồ nữ trang, đồ kim hoàn, đồ trang sức",
    image: require("./data/4000B2_627.jpg"),
    sound: require("./data/4000B2_jewelry.mp3"),
  },
  {
    voc: "land",
    meaning: "hạ cánh (từ máy bay), lên bờ (từ tàu thủy)",
    image: require("./data/4000B2_628.jpg"),
    sound: require("./data/4000B2_land.mp3"),
  },
  {
    voc: "meteor",
    meaning: "sao sa, sao băng",
    image: require("./data/4000B2_629.jpg"),
    sound: require("./data/4000B2_meteor.mp3"),
  },
  {
    voc: "monster",
    meaning: "quái vật, yêu quái",
    image: require("./data/4000B2_630.jpg"),
    sound: require("./data/4000B2_monster.mp3"),
  },
  {
    voc: "northern",
    meaning: "hướng bắc, phương bắc",
    image: require("./data/4000B2_631.jpg"),
    sound: require("./data/4000B2_northern.mp3"),
  },
  {
    voc: "remote",
    meaning: "xa, xa xôi, xa xăm, hẻo lánh",
    image: require("./data/4000B2_632.jpg"),
    sound: require("./data/4000B2_remote.mp3"),
  },
  {
    voc: "southern",
    meaning: "hướng Nam, phương Nam",
    image: require("./data/4000B2_633.jpg"),
    sound: require("./data/4000B2_southern.mp3"),
  },
  {
    voc: "statue",
    meaning: "bức tượng",
    image: require("./data/4000B2_634.jpg"),
    sound: require("./data/4000B2_statue.mp3"),
  },
  {
    voc: "steam",
    meaning: "hơi nước",
    image: require("./data/4000B2_635.jpg"),
    sound: require("./data/4000B2_steam.mp3"),
  },
  {
    voc: "submit",
    meaning: "chịu, cam chịu, quy phục, đệ trình",
    image: require("./data/4000B2_636.jpg"),
    sound: require("./data/4000B2_submit.mp3"),
  },
  {
    voc: "temple",
    meaning: "đền thờ, miếu, thánh thất, thánh đường",
    image: require("./data/4000B2_637.jpg"),
    sound: require("./data/4000B2_temple.mp3"),
  },
  {
    voc: "upper",
    meaning: "trên, cao, thượng",
    image: require("./data/4000B2_638.jpg"),
    sound: require("./data/4000B2_upper.mp3"),
  },
  {
    voc: "weed",
    meaning: "cỏ dại",
    image: require("./data/4000B2_639.jpg"),
    sound: require("./data/4000B2_weed.mp3"),
  },
  {
    voc: "wing",
    meaning: "cánh (chim, sâu bọ)",
    image: require("./data/4000B2_640.jpg"),
    sound: require("./data/4000B2_wing.mp3"),
  },
  {
    voc: "arrow",
    meaning: "mũi tên",
    image: require("./data/4000B2_641.jpg"),
    sound: require("./data/4000B2_arrow.mp3"),
  },
  {
    voc: "battle",
    meaning: "trận đánh; cuộc chiến đấu",
    image: require("./data/4000B2_642.jpg"),
    sound: require("./data/4000B2_battle.mp3"),
  },
  {
    voc: "bow",
    meaning: "cái cung (bắn tên)",
    image: require("./data/4000B2_643.jpg"),
    sound: require("./data/4000B2_bow.mp3"),
  },
  {
    voc: "brave",
    meaning: "gan dạ, can đảm, dũng cảm",
    image: require("./data/4000B2_644.jpg"),
    sound: require("./data/4000B2_brave.mp3"),
  },
  {
    voc: "chief",
    meaning: "thủ lĩnh, lãnh tụ,&nbsp;người đứng đầu; trưởng",
    image: require("./data/4000B2_645.jpg"),
    sound: require("./data/4000B2_chief.mp3"),
  },
  {
    voc: "disadvantage",
    meaning: "sự bất lợi; thế bất lợi,&nbsp;sự thiệt hại, mối tổn thất",
    image: require("./data/4000B2_646.jpg"),
    sound: require("./data/4000B2_disadvantage.mp3"),
  },
  {
    voc: "enemy",
    meaning: "kẻ thù, kẻ địch",
    image: require("./data/4000B2_647.jpg"),
    sound: require("./data/4000B2_enemy.mp3"),
  },
  {
    voc: "entrance",
    meaning: "sự đi vào, lối vào",
    image: require("./data/4000B2_648.jpg"),
    sound: require("./data/4000B2_entrance.mp3"),
  },
  {
    voc: "hardly",
    meaning: "khó khăn, chật vật",
    image: require("./data/4000B2_649.jpg"),
    sound: require("./data/4000B2_hardly.mp3"),
  },
  {
    voc: "intend",
    meaning: "định, có ý định, có ý muốn",
    image: require("./data/4000B2_650.jpg"),
    sound: require("./data/4000B2_intend.mp3"),
  },
  {
    voc: "laughter",
    meaning: "sự cười, tiếng cười to",
    image: require("./data/4000B2_651.jpg"),
    sound: require("./data/4000B2_laughter.mp3"),
  },
  {
    voc: "log",
    meaning: "khúc gỗ&nbsp;",
    image: require("./data/4000B2_652.jpg"),
    sound: require("./data/4000B2_log.mp3"),
  },
  {
    voc: "military",
    meaning: "quân đội,&nbsp;(thuộc) quân đội",
    image: require("./data/4000B2_653.jpg"),
    sound: require("./data/4000B2_military.mp3"),
  },
  {
    voc: "obey",
    meaning: "vâng lời, nghe lời, tuân theo, tuân lệnh",
    image: require("./data/4000B2_654.jpg"),
    sound: require("./data/4000B2_obey.mp3"),
  },
  {
    voc: "secure",
    meaning: "chiếm được, tìm được, đạt được",
    image: require("./data/4000B2_655.jpg"),
    sound: require("./data/4000B2_secure.mp3"),
  },
  {
    voc: "steady",
    meaning: "vững vàng, bình tĩnh, điềm tĩnh, vững chắc",
    image: require("./data/4000B2_656.jpg"),
    sound: require("./data/4000B2_steady.mp3"),
  },
  {
    voc: "trust",
    meaning: "tin, tin cậy, tín nhiệm; trông cậy",
    image: require("./data/4000B2_657.jpg"),
    sound: require("./data/4000B2_trust.mp3"),
  },
  {
    voc: "twist",
    meaning: "xoắn, vặn, xe, bện, kết",
    image: require("./data/4000B2_658.jpg"),
    sound: require("./data/4000B2_twist.mp3"),
  },
  {
    voc: "unless",
    meaning: "trừ khi, nếu không",
    image: require("./data/4000B2_659.jpg"),
    sound: require("./data/4000B2_unless.mp3"),
  },
  {
    voc: "weapon",
    meaning: "vũ khí",
    image: require("./data/4000B2_660.jpg"),
    sound: require("./data/4000B2_weapon.mp3"),
  },
  {
    voc: "chest",
    meaning: "ngực",
    image: require("./data/4000B2_661.jpg"),
    sound: require("./data/4000B2_chest.mp3"),
  },
  {
    voc: "confidence",
    meaning: "sự tin chắc, sự quả quyết, sự tự tin",
    image: require("./data/4000B2_662.jpg"),
    sound: require("./data/4000B2_confidence.mp3"),
  },
  {
    voc: "consequence",
    meaning: "hậu quả, hệ quả, kết quả, tầm quan trọng",
    image: require("./data/4000B2_663.jpg"),
    sound: require("./data/4000B2_consequence.mp3"),
  },
  {
    voc: "disaster",
    meaning: "tai hoạ, thảm hoạ",
    image: require("./data/4000B2_664.jpg"),
    sound: require("./data/4000B2_disaster.mp3"),
  },
  {
    voc: "disturb",
    meaning: "quấy rầy, làm phiền",
    image: require("./data/4000B2_665.jpg"),
    sound: require("./data/4000B2_disturb.mp3"),
  },
  {
    voc: "estimate",
    meaning: "đánh giá; ước lượng",
    image: require("./data/4000B2_666.jpg"),
    sound: require("./data/4000B2_estimate.mp3"),
  },
  {
    voc: "honor",
    meaning: "tôn kính, kính trọng",
    image: require("./data/4000B2_667.jpg"),
    sound: require("./data/4000B2_honor.mp3"),
  },
  {
    voc: "impress",
    meaning: "gây ấn tượng; làm cảm động, làm cảm kích",
    image: require("./data/4000B2_668.jpg"),
    sound: require("./data/4000B2_impress.mp3"),
  },
  {
    voc: "marathon",
    meaning: "cuộc chạy đua maratông",
    image: require("./data/4000B2_669.jpg"),
    sound: require("./data/4000B2_marathon.mp3"),
  },
  {
    voc: "narrow",
    meaning: "hẹp, chật hẹp, eo hẹp",
    image: require("./data/4000B2_670.jpg"),
    sound: require("./data/4000B2_narrow.mp3"),
  },
  {
    voc: "pale",
    meaning: "tái, nhợt nhạt, xanh xám",
    image: require("./data/4000B2_671.jpg"),
    sound: require("./data/4000B2_pale.mp3"),
  },
  {
    voc: "rough",
    meaning: "ráp, nhám, xù xì, gồ ghề,&nbsp;dữ dội, mạnh, hung dữ",
    image: require("./data/4000B2_672.jpg"),
    sound: require("./data/4000B2_rough.mp3"),
  },
  {
    voc: "satisfy",
    meaning: "làm thoả mãn, làm vừa lòng, đáp ứng",
    image: require("./data/4000B2_673.jpg"),
    sound: require("./data/4000B2_satisfy.mp3"),
  },
  {
    voc: "scream",
    meaning: "hét lên, kêu thất thanh; kêu inh ỏi, rít lên (còi tàu...)",
    image: require("./data/4000B2_674.jpg"),
    sound: require("./data/4000B2_scream.mp3"),
  },
  {
    voc: "sensitive",
    meaning: "nhạy cảm",
    image: require("./data/4000B2_675.jpg"),
    sound: require("./data/4000B2_sensitive.mp3"),
  },
  {
    voc: "shade",
    meaning: "bóng, bóng tối, bóng râm",
    image: require("./data/4000B2_676.jpg"),
    sound: require("./data/4000B2_shade.mp3"),
  },
  {
    voc: "supplement",
    meaning: "bổ sung, phụ thêm vào",
    image: require("./data/4000B2_677.jpg"),
    sound: require("./data/4000B2_supplement.mp3"),
  },
  {
    voc: "terror",
    meaning: "sự kinh hãi, sự khiếp sợ",
    image: require("./data/4000B2_678.jpg"),
    sound: require("./data/4000B2_terror.mp3"),
  },
  {
    voc: "threat",
    meaning: "sự đe doạ, lời hăm dọa",
    image: require("./data/4000B2_679.jpg"),
    sound: require("./data/4000B2_threat.mp3"),
  },
  {
    voc: "victim",
    meaning: "nạn nhân",
    image: require("./data/4000B2_680.jpg"),
    sound: require("./data/4000B2_victim.mp3"),
  },
  {
    voc: "ancestor",
    meaning: "ông bà, tổ tiên",
    image: require("./data/4000B2_681.jpg"),
    sound: require("./data/4000B2_ancestor.mp3"),
  },
  {
    voc: "angle",
    meaning: "góc,&nbsp;quan điểm, khía cạnh",
    image: require("./data/4000B2_682.jpg"),
    sound: require("./data/4000B2_angle.mp3"),
  },
  {
    voc: "boot",
    meaning: "giày ống (bốt)",
    image: require("./data/4000B2_683.jpg"),
    sound: require("./data/4000B2_boot.mp3"),
  },
  {
    voc: "border",
    meaning: "bờ, mép, vỉa, lề, biên giới, ranh giới",
    image: require("./data/4000B2_684.jpg"),
    sound: require("./data/4000B2_border.mp3"),
  },
  {
    voc: "congratulate",
    meaning: "chúc mừng, khen ngợi",
    image: require("./data/4000B2_685.jpg"),
    sound: require("./data/4000B2_congratulate.mp3"),
  },
  {
    voc: "frame",
    meaning: "khung (ảnh, cửa, xe...), sườn (tàu, nhà...)",
    image: require("./data/4000B2_686.jpg"),
    sound: require("./data/4000B2_frame.mp3"),
  },
  {
    voc: "heaven",
    meaning: "thiên đường&nbsp;",
    image: require("./data/4000B2_687.jpg"),
    sound: require("./data/4000B2_heaven.mp3"),
  },
  {
    voc: "incredible",
    meaning: "không thể tin được, lạ thường",
    image: require("./data/4000B2_688.jpg"),
    sound: require("./data/4000B2_incredible.mp3"),
  },
  {
    voc: "legend",
    meaning: "truyện cổ tích, truyền thuyết, huyền thoại",
    image: require("./data/4000B2_689.jpg"),
    sound: require("./data/4000B2_legend.mp3"),
  },
  {
    voc: "praise",
    meaning: "khen ngợi",
    image: require("./data/4000B2_690.jpg"),
    sound: require("./data/4000B2_praise.mp3"),
  },
  {
    voc: "proceed",
    meaning: "đi đến,&nbsp;làm, hành động",
    image: require("./data/4000B2_691.jpg"),
    sound: require("./data/4000B2_proceed.mp3"),
  },
  {
    voc: "pure",
    meaning: "trong sạch, nguyên chất, tinh khiết",
    image: require("./data/4000B2_692.jpg"),
    sound: require("./data/4000B2_pure.mp3"),
  },
  {
    voc: "relative",
    meaning: "bà con thân thuộc,&nbsp;họ hàng",
    image: require("./data/4000B2_693.jpg"),
    sound: require("./data/4000B2_relative.mp3"),
  },
  {
    voc: "senior",
    meaning: "nhiều tuổi hơn, cao cấp hơn, lâu năm hơn",
    image: require("./data/4000B2_694.jpg"),
    sound: require("./data/4000B2_senior.mp3"),
  },
  {
    voc: "silent",
    meaning: "yên lặng, yên tĩnh, tĩnh mịch, thanh vắng",
    image: require("./data/4000B2_695.jpg"),
    sound: require("./data/4000B2_silent.mp3"),
  },
  {
    voc: "sink; sank",
    meaning: "chìm",
    image: require("./data/4000B2_696.jpg"),
    sound: require("./data/4000B2_sink.mp3"),
  },
  {
    voc: "superior",
    meaning: "cao, cao cấp,&nbsp;khá hơn, nhiều hơn,&nbsp;tốt, giỏi",
    image: require("./data/4000B2_697.jpg"),
    sound: require("./data/4000B2_superior.mp3"),
  },
  {
    voc: "surround",
    meaning: "bao quanh, vây quanh",
    image: require("./data/4000B2_698.jpg"),
    sound: require("./data/4000B2_surround.mp3"),
  },
  {
    voc: "thick",
    meaning: "dày, dày đặc, rậm, rậm rạp",
    image: require("./data/4000B2_699.jpg"),
    sound: require("./data/4000B2_thick.mp3"),
  },
  {
    voc: "wrap",
    meaning: "bao phủ, gói, quấn",
    image: require("./data/4000B2_700.jpg"),
    sound: require("./data/4000B2_wrap.mp3"),
  },
  {
    voc: "abroad",
    meaning: "ở nước ngoài, ra nước ngoài",
    image: require("./data/4000B2_701.jpg"),
    sound: require("./data/4000B2_abroad.mp3"),
  },
  {
    voc: "anger",
    meaning: "chọc tức, làm tức giận",
    image: require("./data/4000B2_702.jpg"),
    sound: require("./data/4000B2_anger.mp3"),
  },
  {
    voc: "bride",
    meaning: "cô dâu",
    image: require("./data/4000B2_703.jpg"),
    sound: require("./data/4000B2_bride.mp3"),
  },
  {
    voc: "brief",
    meaning: "ngắn gọn, vắn tắt",
    image: require("./data/4000B2_704.jpg"),
    sound: require("./data/4000B2_brief.mp3"),
  },
  {
    voc: "chase",
    meaning: "săn, săn đuổi,&nbsp;đuổi, xua đuổi",
    image: require("./data/4000B2_705.jpg"),
    sound: require("./data/4000B2_chase.mp3"),
  },
  {
    voc: "disappoint",
    meaning: "làm thất vọng,&nbsp;làm hỏng, làm thất bại (kế hoạch của ai)",
    image: require("./data/4000B2_706.jpg"),
    sound: require("./data/4000B2_disappoint.mp3"),
  },
  {
    voc: "dive",
    meaning:
      "lặn,&nbsp;nhảy lao đầu xuống (nước...),&nbsp;bổ nhào xuống (máy bay)",
    image: require("./data/4000B2_707.jpg"),
    sound: require("./data/4000B2_dive.mp3"),
  },
  {
    voc: "exchange",
    meaning: "đổi, đổi chác, trao đổi",
    image: require("./data/4000B2_708.jpg"),
    sound: require("./data/4000B2_exchange.mp3"),
  },
  {
    voc: "favor",
    meaning:
      "verb: bênh vực, giúp đỡ, ủng hộ<div>noun:&nbsp;thiện ý; sự quý mến,&nbsp;sự đồng ý, sự giúp đỡ</div>",
    image: require("./data/4000B2_709.jpg"),
    sound: require("./data/4000B2_favor.mp3"),
  },
  {
    voc: "fee",
    meaning: "tiền thù lao, lệ phí",
    image: require("./data/4000B2_710.jpg"),
    sound: require("./data/4000B2_fee.mp3"),
  },
  {
    voc: "forever",
    meaning: "mãi mãi, vĩnh viễn",
    image: require("./data/4000B2_711.jpg"),
    sound: require("./data/4000B2_forever.mp3"),
  },
  {
    voc: "guy",
    meaning: "anh chàng, gã",
    image: require("./data/4000B2_712.jpg"),
    sound: require("./data/4000B2_guy.mp3"),
  },
  {
    voc: "lovely",
    meaning: "đẹp đẽ, xinh, đáng yêu, dễ thương",
    image: require("./data/4000B2_713.jpg"),
    sound: require("./data/4000B2_lovely.mp3"),
  },
  {
    voc: "mood",
    meaning: "tâm trạng; tính khí, tâm tính, tính tình",
    image: require("./data/4000B2_714.jpg"),
    sound: require("./data/4000B2_mood.mp3"),
  },
  {
    voc: "palace",
    meaning: "cung điện; lâu đài",
    image: require("./data/4000B2_715.jpg"),
    sound: require("./data/4000B2_palace.mp3"),
  },
  {
    voc: "permit",
    meaning: "cho phép,&nbsp;giấy phép",
    image: require("./data/4000B2_716.jpg"),
    sound: require("./data/4000B2_permit.mp3"),
  },
  {
    voc: "protest",
    meaning: "phản đối, kháng nghị, biểu tình",
    image: require("./data/4000B2_717.jpg"),
    sound: require("./data/4000B2_protest.mp3"),
  },
  {
    voc: "sculpture",
    meaning: "điêu khắc, chạm trổ;&nbsp;công trình điêu khắc",
    image: require("./data/4000B2_718.jpg"),
    sound: require("./data/4000B2_sculpture.mp3"),
  },
  {
    voc: "tribe",
    meaning: "bộ lạc",
    image: require("./data/4000B2_719.jpg"),
    sound: require("./data/4000B2_tribe.mp3"),
  },
  {
    voc: "youth",
    meaning: "tuổi trẻ, tuổi xuân, tuổi niên thiếu",
    image: require("./data/4000B2_720.jpg"),
    sound: require("./data/4000B2_youth.mp3"),
  },
  {
    voc: "basis",
    meaning: "phương pháp, nền tảng, cơ sở",
    image: require("./data/4000B2_721.jpg"),
    sound: require("./data/4000B2_basis.mp3"),
  },
  {
    voc: "biology",
    meaning: "sinh vật học, sinh học",
    image: require("./data/4000B2_722.jpg"),
    sound: require("./data/4000B2_biology.mp3"),
  },
  {
    voc: "cage",
    meaning: "lồng, chuồng, cũi",
    image: require("./data/4000B2_723.jpg"),
    sound: require("./data/4000B2_cage.mp3"),
  },
  {
    voc: "colleague",
    meaning: "đồng nghiệp, bạn&nbsp;đồng nghiệp",
    image: require("./data/4000B2_724.jpg"),
    sound: require("./data/4000B2_colleague.mp3"),
  },
  {
    voc: "colony",
    meaning: "thuộc địa,&nbsp;kiều dân; khu kiều dân",
    image: require("./data/4000B2_725.jpg"),
    sound: require("./data/4000B2_colony.mp3"),
  },
  {
    voc: "debate",
    meaning: "tranh luận, tranh cãi, bàn cãi (một vấn đề...)",
    image: require("./data/4000B2_726.jpg"),
    sound: require("./data/4000B2_debate.mp3"),
  },
  {
    voc: "depart",
    meaning: "khởi hành,&nbsp;rời khỏi, ra đi",
    image: require("./data/4000B2_727.jpg"),
    sound: require("./data/4000B2_depart.mp3"),
  },
  {
    voc: "depress",
    meaning: "làm chán nản, làm buồn",
    image: require("./data/4000B2_728.jpg"),
    sound: require("./data/4000B2_depress.mp3"),
  },
  {
    voc: "factual",
    meaning: "(thuộc) sự thực, có thật",
    image: require("./data/4000B2_729.jpg"),
    sound: require("./data/4000B2_factual.mp3"),
  },
  {
    voc: "fascinate",
    meaning: "mê hoặc, quyến rũ",
    image: require("./data/4000B2_730.jpg"),
    sound: require("./data/4000B2_fascinate.mp3"),
  },
  {
    voc: "mission",
    meaning: "sứ mệnh, nhiệm vụ",
    image: require("./data/4000B2_731.jpg"),
    sound: require("./data/4000B2_mission.mp3"),
  },
  {
    voc: "nevertheless",
    meaning: "tuy nhiên, tuy thế mà",
    image: require("./data/4000B2_732.jpg"),
    sound: require("./data/4000B2_nevertheless.mp3"),
  },
  {
    voc: "occupation",
    meaning: "sự chiếm, sự giữ,&nbsp;nghề nghiệp; công việc",
    image: require("./data/4000B2_733.jpg"),
    sound: require("./data/4000B2_occupation.mp3"),
  },
  {
    voc: "overseas",
    meaning: "ngoài nước, hải ngoại",
    image: require("./data/4000B2_734.jpg"),
    sound: require("./data/4000B2_overseas.mp3"),
  },
  {
    voc: "persuade",
    meaning: "làm cho tin; thuyết phục",
    image: require("./data/4000B2_735.jpg"),
    sound: require("./data/4000B2_persuade.mp3"),
  },
  {
    voc: "route",
    meaning: "tuyến đường, đường đi",
    image: require("./data/4000B2_736.jpg"),
    sound: require("./data/4000B2_route.mp3"),
  },
  {
    voc: "ruins",
    meaning: "đổ nát, phế tích",
    image: require("./data/4000B2_737.jpg"),
    sound: require("./data/4000B2_ruins.mp3"),
  },
  {
    voc: "scholar",
    meaning:
      "người có học thức, nhà thông thái;&nbsp;<div>người được cấp học bổng,&nbsp;học bổng</div>",
    image: require("./data/4000B2_738.jpg"),
    sound: require("./data/4000B2_scholar.mp3"),
  },
  {
    voc: "significant",
    meaning: "quan trọng, trọng đại, đáng chú ý",
    image: require("./data/4000B2_739.jpg"),
    sound: require("./data/4000B2_significant.mp3"),
  },
  {
    voc: "volcano",
    meaning: "núi lửa",
    image: require("./data/4000B2_740.jpg"),
    sound: require("./data/4000B2_volcano.mp3"),
  },
  {
    voc: "broad",
    meaning: "rộng, gồm nhiều loại",
    image: require("./data/4000B2_741.jpg"),
    sound: require("./data/4000B2_broad.mp3"),
  },
  {
    voc: "bush",
    meaning: "bụi cây, bụi rậm",
    image: require("./data/4000B2_742.jpg"),
    sound: require("./data/4000B2_bush.mp3"),
  },
  {
    voc: "capable",
    meaning: "có khả năng,&nbsp;có tài, có năng lực giỏi",
    image: require("./data/4000B2_743.jpg"),
    sound: require("./data/4000B2_capable.mp3"),
  },
  {
    voc: "cheat",
    meaning: "gian lận,&nbsp;lừa, lừa đảo (ai)",
    image: require("./data/4000B2_744.jpg"),
    sound: require("./data/4000B2_cheat.mp3"),
  },
  {
    voc: "concentrate",
    meaning: "tập trung",
    image: require("./data/4000B2_745.jpg"),
    sound: require("./data/4000B2_concentrate.mp3"),
  },
  {
    voc: "conclude",
    meaning: "kết luận,&nbsp;giải quyết, dàn xếp",
    image: require("./data/4000B2_746.jpg"),
    sound: require("./data/4000B2_conclude.mp3"),
  },
  {
    voc: "confident",
    meaning: "tự tin, tin chắc, tin tưởng, tin cậy",
    image: require("./data/4000B2_747.jpg"),
    sound: require("./data/4000B2_confident.mp3"),
  },
  {
    voc: "considerable",
    meaning: "đáng kể, to tát, có vai vế",
    image: require("./data/4000B2_748.jpg"),
    sound: require("./data/4000B2_considerable.mp3"),
  },
  {
    voc: "convey",
    meaning:
      "truyền (âm thanh, hương vị, lệnh, tin); truyền đạt, chuyển<div>chở, chuyên chở, vận chuyển</div>",
    image: require("./data/4000B2_749.jpg"),
    sound: require("./data/4000B2_convey.mp3"),
  },
  {
    voc: "definite",
    meaning: "rõ ràng,&nbsp;xác định, định rõ, hiển nhiên",
    image: require("./data/4000B2_750.jpg"),
    sound: require("./data/4000B2_definite.mp3"),
  },
  {
    voc: "delight",
    meaning: "sự vui sướng,&nbsp;điều thích thú",
    image: require("./data/4000B2_751.jpg"),
    sound: require("./data/4000B2_delight.mp3"),
  },
  {
    voc: "destination",
    meaning: "đích đến,&nbsp;nơi đi tới",
    image: require("./data/4000B2_752.jpg"),
    sound: require("./data/4000B2_destination.mp3"),
  },
  {
    voc: "dictate",
    meaning: "đọc chính tả,&nbsp;ra lệnh",
    image: require("./data/4000B2_753.jpg"),
    sound: require("./data/4000B2_dictate.mp3"),
  },
  {
    voc: "edge",
    meaning: "bờ, gờ, cạnh (hố sâu...); rìa, lề (rừng, cuốn sách...)",
    image: require("./data/4000B2_754.jpg"),
    sound: require("./data/4000B2_edge.mp3"),
  },
  {
    voc: "path",
    meaning: "đường đi; quỹ đạo",
    image: require("./data/4000B2_755.jpg"),
    sound: require("./data/4000B2_path.mp3"),
  },
  {
    voc: "resort",
    meaning: "dùng đến, cầu đến, nhờ vào",
    image: require("./data/4000B2_756.jpg"),
    sound: require("./data/4000B2_resort.mp3"),
  },
  {
    voc: "shadow",
    meaning:
      "bóng (của bức tranh..),&nbsp;chỗ tối (trong gian phòng...),&nbsp;bóng tối, bóng râm, bóng mát",
    image: require("./data/4000B2_757.jpg"),
    sound: require("./data/4000B2_shadow.mp3"),
  },
  {
    voc: "succeed",
    meaning: "thành công,&nbsp;kế nghiệp,&nbsp;kế tiếp",
    image: require("./data/4000B2_758.jpg"),
    sound: require("./data/4000B2_succeed.mp3"),
  },
  {
    voc: "suspect",
    meaning: "nghi ngờ, hoài nghi;&nbsp;người khả nghi",
    image: require("./data/4000B2_759.jpg"),
    sound: require("./data/4000B2_suspect.mp3"),
  },
  {
    voc: "valley",
    meaning: "thung lũng,&nbsp;&nbsp;(kiến trúc) khe mái",
    image: require("./data/4000B2_760.jpg"),
    sound: require("./data/4000B2_valley.mp3"),
  },
  {
    voc: "admire",
    meaning: "khâm phục,&nbsp;ngưỡng mộ",
    image: require("./data/4000B2_761.jpg"),
    sound: require("./data/4000B2_admire.mp3"),
  },
  {
    voc: "aid",
    meaning: "trợ giúp, thêm vào, phụ vào",
    image: require("./data/4000B2_762.jpg"),
    sound: require("./data/4000B2_aid.mp3"),
  },
  {
    voc: "attempt",
    meaning: "cố gắng; thử,&nbsp;gắng, chiếm lấy",
    image: require("./data/4000B2_763.jpg"),
    sound: require("./data/4000B2_attempt.mp3"),
  },
  {
    voc: "authority",
    meaning:
      "uy quyền, quyền lực, quyền thế<div>(số nhiều) nhà cầm quyền, nhà chức trách</div>",
    image: require("./data/4000B2_764.jpg"),
    sound: require("./data/4000B2_authority.mp3"),
  },
  {
    voc: "capital",
    meaning: "thủ đô, thủ phủ",
    image: require("./data/4000B2_765.jpg"),
    sound: require("./data/4000B2_capital.mp3"),
  },
  {
    voc: "cooperate",
    meaning: "hợp tác",
    image: require("./data/4000B2_766.jpg"),
    sound: require("./data/4000B2_cooperate.mp3"),
  },
  {
    voc: "defend",
    meaning: "che chở, bảo vệ, phòng thủ, tự vệ",
    image: require("./data/4000B2_767.jpg"),
    sound: require("./data/4000B2_defend.mp3"),
  },
  {
    voc: "destruction",
    meaning: "sự phá huỷ,&nbsp;tình trạng bị tàn phá",
    image: require("./data/4000B2_768.jpg"),
    sound: require("./data/4000B2_destruction.mp3"),
  },
  {
    voc: "disorder",
    meaning: "sự mất trật tự, sự bừa bãi, sự lộn xộn",
    image: require("./data/4000B2_769.jpg"),
    sound: require("./data/4000B2_disorder.mp3"),
  },
  {
    voc: "division",
    meaning: "sự chia; sự phân chia",
    image: require("./data/4000B2_770.jpg"),
    sound: require("./data/4000B2_division.mp3"),
  },
  {
    voc: "enable",
    meaning: "làm cho có thể",
    image: require("./data/4000B2_771.jpg"),
    sound: require("./data/4000B2_enable.mp3"),
  },
  {
    voc: "frustrate",
    meaning: "làm thất bại, làm hỏng,&nbsp;làm thất vọng, làm vỡ mộng",
    image: require("./data/4000B2_772.jpg"),
    sound: require("./data/4000B2_frustrate.mp3"),
  },
  {
    voc: "govern",
    meaning:
      "cai trị, thống trị, cầm quyền (một nước), điều hành (chính quyền)",
    image: require("./data/4000B2_773.jpg"),
    sound: require("./data/4000B2_govern.mp3"),
  },
  {
    voc: "plenty",
    meaning: "sự phong phú, sự dồi dào, sự có nhiều",
    image: require("./data/4000B2_774.jpg"),
    sound: require("./data/4000B2_plenty.mp3"),
  },
  {
    voc: "relieve",
    meaning: "làm dịu,&nbsp;làm nhẹ bớt, giảm bớt",
    image: require("./data/4000B2_775.jpg"),
    sound: require("./data/4000B2_relieve.mp3"),
  },
  {
    voc: "reputation",
    meaning: "danh tiếng",
    image: require("./data/4000B2_776.jpg"),
    sound: require("./data/4000B2_reputation.mp3"),
  },
  {
    voc: "royal",
    meaning: "(thuộc) hoàng gia",
    image: require("./data/4000B2_777.jpg"),
    sound: require("./data/4000B2_royal.mp3"),
  },
  {
    voc: "slave",
    meaning: "người nô lệ",
    image: require("./data/4000B2_778.jpg"),
    sound: require("./data/4000B2_slave.mp3"),
  },
  {
    voc: "struggle",
    meaning: "đấu tranh, chống lại,&nbsp;vật lộn",
    image: require("./data/4000B2_779.jpg"),
    sound: require("./data/4000B2_struggle.mp3"),
  },
  {
    voc: "stupid",
    meaning: "ngu dại, ngớ ngẩn",
    image: require("./data/4000B2_780.jpg"),
    sound: require("./data/4000B2_stupid.mp3"),
  },
  {
    voc: "citizen",
    meaning: "công dân",
    image: require("./data/4000B2_781.jpg"),
    sound: require("./data/4000B2_citizen.mp3"),
  },
  {
    voc: "council",
    meaning: "hội đồng",
    image: require("./data/4000B2_782.jpg"),
    sound: require("./data/4000B2_council.mp3"),
  },
  {
    voc: "declare",
    meaning: "khai báo, bày tỏ",
    image: require("./data/4000B2_783.jpg"),
    sound: require("./data/4000B2_declare.mp3"),
  },
  {
    voc: "enormous",
    meaning: "to lớn, khổng lồ",
    image: require("./data/4000B2_784.jpg"),
    sound: require("./data/4000B2_enormous.mp3"),
  },
  {
    voc: "extraordinary",
    meaning: "lạ thường, khác thường, phi thường",
    image: require("./data/4000B2_785.jpg"),
    sound: require("./data/4000B2_extraordinary.mp3"),
  },
  {
    voc: "fog",
    meaning: "sương mù",
    image: require("./data/4000B2_786.jpg"),
    sound: require("./data/4000B2_fog.mp3"),
  },
  {
    voc: "funeral",
    meaning: "lễ tang, đám tang",
    image: require("./data/4000B2_787.jpg"),
    sound: require("./data/4000B2_funeral.mp3"),
  },
  {
    voc: "giant",
    meaning: "khổng lồ",
    image: require("./data/4000B2_788.jpg"),
    sound: require("./data/4000B2_giant.mp3"),
  },
  {
    voc: "impression",
    meaning: "ấn tượng",
    image: require("./data/4000B2_789.jpg"),
    sound: require("./data/4000B2_impression.mp3"),
  },
  {
    voc: "income",
    meaning: "thu nhập",
    image: require("./data/4000B2_790.jpg"),
    sound: require("./data/4000B2_income.mp3"),
  },
  {
    voc: "mad",
    meaning: "điên, cuồng, mất trí",
    image: require("./data/4000B2_791.jpg"),
    sound: require("./data/4000B2_mad.mp3"),
  },
  {
    voc: "ought",
    meaning: "phải, nên",
    image: require("./data/4000B2_792.jpg"),
    sound: require("./data/4000B2_ought.mp3"),
  },
  {
    voc: "resist",
    meaning: "kháng cự, chống lại",
    image: require("./data/4000B2_793.jpg"),
    sound: require("./data/4000B2_resist.mp3"),
  },
  {
    voc: "reveal",
    meaning: "tiết lộ (điều bí mật), phát giác",
    image: require("./data/4000B2_794.jpg"),
    sound: require("./data/4000B2_reveal.mp3"),
  },
  {
    voc: "rid",
    meaning: "giải thoát&nbsp;",
    image: require("./data/4000B2_795.jpg"),
    sound: require("./data/4000B2_rid.mp3"),
  },
  {
    voc: "sword",
    meaning: "gươm, kiếm",
    image: require("./data/4000B2_796.jpg"),
    sound: require("./data/4000B2_sword.mp3"),
  },
  {
    voc: "tale",
    meaning: "truyện, truyện ngắn",
    image: require("./data/4000B2_797.jpg"),
    sound: require("./data/4000B2_tale.mp3"),
  },
  {
    voc: "trap",
    meaning: "bẫy, đặt bẫy",
    image: require("./data/4000B2_798.jpg"),
    sound: require("./data/4000B2_trap.mp3"),
  },
  {
    voc: "trial",
    meaning: "sự thử,&nbsp;(pháp lý) việc xét xử, sự xử án",
    image: require("./data/4000B2_799.jpg"),
    sound: require("./data/4000B2_trial.mp3"),
  },
  {
    voc: "violent",
    meaning: "bạo lực,&nbsp;hung bạo, quá khích",
    image: require("./data/4000B2_800.jpg"),
    sound: require("./data/4000B2_violent.mp3"),
  },
  {
    voc: "admission",
    meaning: "sự cho vào cửa, sự cho vào",
    image: require("./data/4000B2_801.jpg"),
    sound: require("./data/4000B2_admission.mp3"),
  },
  {
    voc: "astronomy",
    meaning: "thiên văn học",
    image: require("./data/4000B2_802.jpg"),
    sound: require("./data/4000B2_astronomy.mp3"),
  },
  {
    voc: "blame",
    meaning: "khiển trách, trách mắng",
    image: require("./data/4000B2_803.jpg"),
    sound: require("./data/4000B2_blame.mp3"),
  },
  {
    voc: "chemistry",
    meaning: "ngành hoá học; môn hoá học",
    image: require("./data/4000B2_804.jpg"),
    sound: require("./data/4000B2_chemistry.mp3"),
  },
  {
    voc: "despite",
    meaning: "dù, mặc dù, không kể, bất chấp",
    image: require("./data/4000B2_805.jpg"),
    sound: require("./data/4000B2_despite.mp3"),
  },
  {
    voc: "dinosaur",
    meaning: "khủng long",
    image: require("./data/4000B2_806.jpg"),
    sound: require("./data/4000B2_dinosaur.mp3"),
  },
  {
    voc: "exhibit",
    meaning: "trưng bày, triển lãm,&nbsp;vật trưng bày, vật triển lãm",
    image: require("./data/4000B2_807.jpg"),
    sound: require("./data/4000B2_exhibit.mp3"),
  },
  {
    voc: "fame",
    meaning: "tiếng tăm, danh tiếng",
    image: require("./data/4000B2_808.jpg"),
    sound: require("./data/4000B2_fame.mp3"),
  },
  {
    voc: "forecast",
    meaning: "dự báo",
    image: require("./data/4000B2_809.jpg"),
    sound: require("./data/4000B2_forecast.mp3"),
  },
  {
    voc: "genius",
    meaning: "thiên tài",
    image: require("./data/4000B2_810.jpg"),
    sound: require("./data/4000B2_genius.mp3"),
  },
  {
    voc: "gentle",
    meaning: "hiền lành, dịu dàng, hoà nhã; nhẹ nhàng",
    image: require("./data/4000B2_811.jpg"),
    sound: require("./data/4000B2_gentle.mp3"),
  },
  {
    voc: "geography",
    meaning: "địa lý",
    image: require("./data/4000B2_812.jpg"),
    sound: require("./data/4000B2_geography.mp3"),
  },
  {
    voc: "interfere",
    meaning: "gây trở ngại, quấy rầy",
    image: require("./data/4000B2_813.jpg"),
    sound: require("./data/4000B2_interfere.mp3"),
  },
  {
    voc: "lightly",
    meaning: "nhẹ, nhẹ nhàng",
    image: require("./data/4000B2_814.jpg"),
    sound: require("./data/4000B2_lightly.mp3"),
  },
  {
    voc: "principal",
    meaning: "hiệu trưởng, người đứng đầu",
    image: require("./data/4000B2_815.jpg"),
    sound: require("./data/4000B2_principal.mp3"),
  },
  {
    voc: "row",
    meaning: "hàng, dây",
    image: require("./data/4000B2_816.jpg"),
    sound: require("./data/4000B2_row.mp3"),
  },
  {
    voc: "shelf",
    meaning: "giá sách, ngăn tủ",
    image: require("./data/4000B2_817.jpg"),
    sound: require("./data/4000B2_shelf.mp3"),
  },
  {
    voc: "spite",
    meaning: "sự thù oán; mối hận thù",
    image: require("./data/4000B2_818.jpg"),
    sound: require("./data/4000B2_spite.mp3"),
  },
  {
    voc: "super",
    meaning: "siêu",
    image: require("./data/4000B2_819.jpg"),
    sound: require("./data/4000B2_super.mp3"),
  },
  {
    voc: "wet",
    meaning: "ẩm; ướt",
    image: require("./data/4000B2_820.jpg"),
    sound: require("./data/4000B2_wet.mp3"),
  },
  {
    voc: "abuse",
    meaning: "lăng mạ, sỉ nhục, chửi rủa",
    image: require("./data/4000B2_821.jpg"),
    sound: require("./data/4000B2_abuse.mp3"),
  },
  {
    voc: "afford",
    meaning: "có đủ sức, có đủ khả năng (làm gì)",
    image: require("./data/4000B2_822.jpg"),
    sound: require("./data/4000B2_afford.mp3"),
  },
  {
    voc: "bake",
    meaning: "nướng (bánh...) bằng lò",
    image: require("./data/4000B2_823.jpg"),
    sound: require("./data/4000B2_bake.mp3"),
  },
  {
    voc: "bean",
    meaning: "đậu",
    image: require("./data/4000B2_824.jpg"),
    sound: require("./data/4000B2_bean.mp3"),
  },
  {
    voc: "candle",
    meaning: "ngọn nến",
    image: require("./data/4000B2_825.jpg"),
    sound: require("./data/4000B2_candle.mp3"),
  },
  {
    voc: "convert",
    meaning: "chuyển đổi, biến đổi",
    image: require("./data/4000B2_826.jpg"),
    sound: require("./data/4000B2_convert.mp3"),
  },
  {
    voc: "debt",
    meaning: "món nợ",
    image: require("./data/4000B2_827.jpg"),
    sound: require("./data/4000B2_debt.mp3"),
  },
  {
    voc: "decrease",
    meaning: "giảm, giảm sút, giảm đi",
    image: require("./data/4000B2_828.jpg"),
    sound: require("./data/4000B2_decrease.mp3"),
  },
  {
    voc: "fault",
    meaning: "sự thiếu sót; khuyết điểm",
    image: require("./data/4000B2_829.jpg"),
    sound: require("./data/4000B2_fault.mp3"),
  },
  {
    voc: "fund",
    meaning: "quỹ",
    image: require("./data/4000B2_830.jpg"),
    sound: require("./data/4000B2_fund.mp3"),
  },
  {
    voc: "generous",
    meaning: "rộng rãi, hào phóng",
    image: require("./data/4000B2_831.jpg"),
    sound: require("./data/4000B2_generous.mp3"),
  },
  {
    voc: "ingredient",
    meaning: "phần hợp thành, thành phần",
    image: require("./data/4000B2_832.jpg"),
    sound: require("./data/4000B2_ingredient.mp3"),
  },
  {
    voc: "insist",
    meaning: "cố nài, nhấn mạnh",
    image: require("./data/4000B2_833.jpg"),
    sound: require("./data/4000B2_insist.mp3"),
  },
  {
    voc: "mess",
    meaning: "tình trạng lộn xộn, tình trạng bừa bộn",
    image: require("./data/4000B2_834.jpg"),
    sound: require("./data/4000B2_mess.mp3"),
  },
  {
    voc: "metal",
    meaning: "kim loại",
    image: require("./data/4000B2_835.jpg"),
    sound: require("./data/4000B2_metal.mp3"),
  },
  {
    voc: "monitor",
    meaning: "giám sát",
    image: require("./data/4000B2_836.jpg"),
    sound: require("./data/4000B2_monitor.mp3"),
  },
  {
    voc: "oppose",
    meaning: "chống lại, đối chọi",
    image: require("./data/4000B2_837.jpg"),
    sound: require("./data/4000B2_oppose.mp3"),
  },
  {
    voc: "passive",
    meaning: "bị động, thụ động",
    image: require("./data/4000B2_838.jpg"),
    sound: require("./data/4000B2_passive.mp3"),
  },
  {
    voc: "quantity",
    meaning: "số lượng",
    image: require("./data/4000B2_839.jpg"),
    sound: require("./data/4000B2_quantity.mp3"),
  },
  {
    voc: "sue",
    meaning: "kiện (ai ra tòa)",
    image: require("./data/4000B2_840.jpg"),
    sound: require("./data/4000B2_sue.mp3"),
  },
  {
    voc: "anxiety",
    meaning: "mối lo âu, mối băn khoăn; sự lo lắng",
    image: require("./data/4000B2_841.jpg"),
    sound: require("./data/4000B2_anxiety.mp3"),
  },
  {
    voc: "army",
    meaning: "quân đội",
    image: require("./data/4000B2_842.jpg"),
    sound: require("./data/4000B2_army.mp3"),
  },
  {
    voc: "billion",
    meaning: "tỉ (tiền tệ)",
    image: require("./data/4000B2_843.jpg"),
    sound: require("./data/4000B2_billion.mp3"),
  },
  {
    voc: "carve",
    meaning: "cắt, lạng (thịt ra từng miếng)",
    image: require("./data/4000B2_844.jpg"),
    sound: require("./data/4000B2_carve.mp3"),
  },
  {
    voc: "consult",
    meaning: "hỏi ý kiến, tham khảo, tư vấn, hội ý",
    image: require("./data/4000B2_845.jpg"),
    sound: require("./data/4000B2_consult.mp3"),
  },
  {
    voc: "emergency",
    meaning: "tình trạng khẩn cấp,&nbsp;trường hợp cấp cứu",
    image: require("./data/4000B2_846.jpg"),
    sound: require("./data/4000B2_emergency.mp3"),
  },
  {
    voc: "fortune",
    meaning: "vận may; sự may mắn",
    image: require("./data/4000B2_847.jpg"),
    sound: require("./data/4000B2_fortune.mp3"),
  },
  {
    voc: "guarantee",
    meaning: "bảo đảm, bảo lânh",
    image: require("./data/4000B2_848.jpg"),
    sound: require("./data/4000B2_guarantee.mp3"),
  },
  {
    voc: "hike",
    meaning: "đi bộ đường dài",
    image: require("./data/4000B2_849.jpg"),
    sound: require("./data/4000B2_hike.mp3"),
  },
  {
    voc: "initial",
    meaning: "đầu, ban đầu",
    image: require("./data/4000B2_850.jpg"),
    sound: require("./data/4000B2_initial.mp3"),
  },
  {
    voc: "intense",
    meaning: "mãnh liệt, dữ dội",
    image: require("./data/4000B2_851.jpg"),
    sound: require("./data/4000B2_intense.mp3"),
  },
  {
    voc: "lend",
    meaning: "cho vay, cho mượn",
    image: require("./data/4000B2_852.jpg"),
    sound: require("./data/4000B2_lend.mp3"),
  },
  {
    voc: "peak",
    meaning: "đỉnh, chỏm chóp (núi)",
    image: require("./data/4000B2_853.jpg"),
    sound: require("./data/4000B2_peak.mp3"),
  },
  {
    voc: "potential",
    meaning: "tiềm tàng",
    image: require("./data/4000B2_854.jpg"),
    sound: require("./data/4000B2_potential.mp3"),
  },
  {
    voc: "pride",
    meaning: "sự kiêu hãnh, sự hãnh diện",
    image: require("./data/4000B2_855.jpg"),
    sound: require("./data/4000B2_pride.mp3"),
  },
  {
    voc: "proof",
    meaning: "bằng chứng",
    image: require("./data/4000B2_856.jpg"),
    sound: require("./data/4000B2_proof.mp3"),
  },
  {
    voc: "quit",
    meaning: "thoát, bỏ, rời",
    image: require("./data/4000B2_857.jpg"),
    sound: require("./data/4000B2_quit.mp3"),
  },
  {
    voc: "spin",
    meaning: "quay, quay tròn",
    image: require("./data/4000B2_858.jpg"),
    sound: require("./data/4000B2_spin.mp3"),
  },
  {
    voc: "tiny",
    meaning: "nhỏ xíu, tí hon",
    image: require("./data/4000B2_859.jpg"),
    sound: require("./data/4000B2_tiny.mp3"),
  },
  {
    voc: "tutor",
    meaning: "gia sư, giáo viên kèm riêng",
    image: require("./data/4000B2_860.jpg"),
    sound: require("./data/4000B2_tutor.mp3"),
  },
  {
    voc: "apparent",
    meaning: "rõ ràng, bày tỏ ra ngoài, thấy rõ ra ngoài",
    image: require("./data/4000B2_861.jpg"),
    sound: require("./data/4000B2_apparent.mp3"),
  },
  {
    voc: "blind",
    meaning: "đui mù",
    image: require("./data/4000B2_862.jpg"),
    sound: require("./data/4000B2_blind.mp3"),
  },
  {
    voc: "calculate",
    meaning: "tính toán",
    image: require("./data/4000B2_863.jpg"),
    sound: require("./data/4000B2_calculate.mp3"),
  },
  {
    voc: "chat",
    meaning: "nói chuyện phiếm, tán gẫu",
    image: require("./data/4000B2_864.jpg"),
    sound: require("./data/4000B2_chat.mp3"),
  },
  {
    voc: "commit",
    meaning: "hứa, cam kết,&nbsp;tống giam",
    image: require("./data/4000B2_865.jpg"),
    sound: require("./data/4000B2_commit.mp3"),
  },
  {
    voc: "compose",
    meaning: "soạn, sáng tác, làm",
    image: require("./data/4000B2_866.jpg"),
    sound: require("./data/4000B2_compose.mp3"),
  },
  {
    voc: "dormitory",
    meaning: "ký túc xá, phòng ngủ tập thể",
    image: require("./data/4000B2_867.jpg"),
    sound: require("./data/4000B2_dormitory.mp3"),
  },
  {
    voc: "exhaust",
    meaning: "làm kiệt quệ, kiệt sức",
    image: require("./data/4000B2_868.jpg"),
    sound: require("./data/4000B2_exhaust.mp3"),
  },
  {
    voc: "greenhouse",
    meaning: "<div>nhà kính (trồng rau, hoa)</div>",
    image: require("./data/4000B2_869.jpg"),
    sound: require("./data/4000B2_greenhouse.mp3"),
  },
  {
    voc: "ignore",
    meaning: "lờ đi, phớt đi, bác bỏ",
    image: require("./data/4000B2_870.jpg"),
    sound: require("./data/4000B2_ignore.mp3"),
  },
  {
    voc: "obvious",
    meaning: "rõ ràng, rành mạch",
    image: require("./data/4000B2_871.jpg"),
    sound: require("./data/4000B2_obvious.mp3"),
  },
  {
    voc: "physics",
    meaning: "vật lý học",
    image: require("./data/4000B2_872.jpg"),
    sound: require("./data/4000B2_physics.mp3"),
  },
  {
    voc: "portion",
    meaning: "phần, phần chia",
    image: require("./data/4000B2_873.jpg"),
    sound: require("./data/4000B2_portion.mp3"),
  },
  {
    voc: "remind",
    meaning: "nhắc nhở, làm nhớ lại (cái gì)",
    image: require("./data/4000B2_874.jpg"),
    sound: require("./data/4000B2_remind.mp3"),
  },
  {
    voc: "secretary",
    meaning: "thư ký, bí thư",
    image: require("./data/4000B2_875.jpg"),
    sound: require("./data/4000B2_secretary.mp3"),
  },
  {
    voc: "severe",
    meaning: "khắt khe (trong thái độ, cách cư xử),&nbsp;khốc liệt, dữ dội",
    image: require("./data/4000B2_876.jpg"),
    sound: require("./data/4000B2_severe.mp3"),
  },
  {
    voc: "talent",
    meaning: "năng khiếu",
    image: require("./data/4000B2_877.jpg"),
    sound: require("./data/4000B2_talent.mp3"),
  },
  {
    voc: "thesis",
    meaning: "luận văn, luận án",
    image: require("./data/4000B2_878.jpg"),
    sound: require("./data/4000B2_thesis.mp3"),
  },
  {
    voc: "uniform",
    meaning: "đồng phục, quân phục",
    image: require("./data/4000B2_879.jpg"),
    sound: require("./data/4000B2_uniform.mp3"),
  },
  {
    voc: "vision",
    meaning: "sự nhìn; sức nhìn",
    image: require("./data/4000B2_880.jpg"),
    sound: require("./data/4000B2_vision.mp3"),
  },
  {
    voc: "absorb",
    meaning: "hút nước, thấm nước, hấp thu",
    image: require("./data/4000B2_881.jpg"),
    sound: require("./data/4000B2_absorb.mp3"),
  },
  {
    voc: "boss",
    meaning: "ông chủ, thủ trưởng",
    image: require("./data/4000B2_882.jpg"),
    sound: require("./data/4000B2_boss.mp3"),
  },
  {
    voc: "committee",
    meaning: "uỷ ban",
    image: require("./data/4000B2_883.jpg"),
    sound: require("./data/4000B2_committee.mp3"),
  },
  {
    voc: "contract",
    meaning: "hợp đồng",
    image: require("./data/4000B2_884.jpg"),
    sound: require("./data/4000B2_contract.mp3"),
  },
  {
    voc: "crew",
    meaning: "ban nhóm, đội (làm việc...)",
    image: require("./data/4000B2_885.jpg"),
    sound: require("./data/4000B2_crew.mp3"),
  },
  {
    voc: "devote",
    meaning: "hiến dâng, dành hết cho",
    image: require("./data/4000B2_886.jpg"),
    sound: require("./data/4000B2_devote.mp3"),
  },
  {
    voc: "dig",
    meaning: "đào bới, xới, cuốc (đất...)",
    image: require("./data/4000B2_887.jpg"),
    sound: require("./data/4000B2_dig.mp3"),
  },
  {
    voc: "dine",
    meaning: "ăn cơm (trưa, tối)",
    image: require("./data/4000B2_888.jpg"),
    sound: require("./data/4000B2_dine.mp3"),
  },
  {
    voc: "donate",
    meaning: "quyên góp, tặng",
    image: require("./data/4000B2_889.jpg"),
    sound: require("./data/4000B2_donate.mp3"),
  },
  {
    voc: "double",
    meaning: "gấp đôi, hai, kép",
    image: require("./data/4000B2_890.jpg"),
    sound: require("./data/4000B2_double.mp3"),
  },
  {
    voc: "elevate",
    meaning: "nâng lên, đưa lên,&nbsp;nâng cao",
    image: require("./data/4000B2_891.jpg"),
    sound: require("./data/4000B2_elevate.mp3"),
  },
  {
    voc: "flavor",
    meaning: "vị ngon, mùi thơm; mùi vị",
    image: require("./data/4000B2_892.jpg"),
    sound: require("./data/4000B2_flavor.mp3"),
  },
  {
    voc: "foundation",
    meaning: "quỹ",
    image: require("./data/4000B2_893.jpg"),
    sound: require("./data/4000B2_foundation.mp3"),
  },
  {
    voc: "generation",
    meaning: "thế hệ",
    image: require("./data/4000B2_894.jpg"),
    sound: require("./data/4000B2_generation.mp3"),
  },
  {
    voc: "handle",
    meaning: "tay cầm",
    image: require("./data/4000B2_895.jpg"),
    sound: require("./data/4000B2_handle.mp3"),
  },
  {
    voc: "layer",
    meaning: "lớp",
    image: require("./data/4000B2_896.jpg"),
    sound: require("./data/4000B2_layer.mp3"),
  },
  {
    voc: "mud",
    meaning: "bùn ((nghĩa đen) &amp; (nghĩa bóng))",
    image: require("./data/4000B2_897.jpg"),
    sound: require("./data/4000B2_mud.mp3"),
  },
  {
    voc: "smooth",
    meaning: "nhẵn, trơn, mượt",
    image: require("./data/4000B2_898.jpg"),
    sound: require("./data/4000B2_smooth.mp3"),
  },
  {
    voc: "soil",
    meaning: "đất",
    image: require("./data/4000B2_899.jpg"),
    sound: require("./data/4000B2_soil.mp3"),
  },
  {
    voc: "unique",
    meaning: "độc đáo",
    image: require("./data/4000B2_900.jpg"),
    sound: require("./data/4000B2_unique.mp3"),
  },
  {
    voc: "chamber",
    meaning: "phòng ngủ",
    image: require("./data/4000B2_901.jpg"),
    sound: require("./data/4000B2_chamber.mp3"),
  },
  {
    voc: "deny",
    meaning: "từ chối, phản đối, phủ nhận",
    image: require("./data/4000B2_902.jpg"),
    sound: require("./data/4000B2_deny.mp3"),
  },
  {
    voc: "document",
    meaning: "văn bản, tài liệu, tư liệu",
    image: require("./data/4000B2_903.jpg"),
    sound: require("./data/4000B2_document.mp3"),
  },
  {
    voc: "emphasize",
    meaning: "nhấn mạnh, làm nổi bật",
    image: require("./data/4000B2_904.jpg"),
    sound: require("./data/4000B2_emphasize.mp3"),
  },
  {
    voc: "fever",
    meaning: "sốt, bệnh sốt",
    image: require("./data/4000B2_905.jpg"),
    sound: require("./data/4000B2_fever.mp3"),
  },
  {
    voc: "flu",
    meaning: "cảm cúm, bệnh cúm",
    image: require("./data/4000B2_906.jpg"),
    sound: require("./data/4000B2_flu.mp3"),
  },
  {
    voc: "freeze",
    meaning: "đóng băng, lạnh cứng",
    image: require("./data/4000B2_907.jpg"),
    sound: require("./data/4000B2_freeze.mp3"),
  },
  {
    voc: "gesture",
    meaning: "điệu bộ, cử chỉ, động tác",
    image: require("./data/4000B2_908.jpg"),
    sound: require("./data/4000B2_gesture.mp3"),
  },
  {
    voc: "interrupt",
    meaning: "làm gián đoạn,&nbsp;ngắt lời",
    image: require("./data/4000B2_909.jpg"),
    sound: require("./data/4000B2_interrupt.mp3"),
  },
  {
    voc: "last",
    meaning: "tồn tại, kéo dài; giữ lâu bền",
    image: require("./data/4000B2_910.jpg"),
    sound: require("./data/4000B2_last.mp3"),
  },
  {
    voc: "likeness",
    meaning: "tính chất giống; sự giống",
    image: require("./data/4000B2_911.jpg"),
    sound: require("./data/4000B2_likeness.mp3"),
  },
  {
    voc: "moreover",
    meaning: "hơn nữa, ngoài ra",
    image: require("./data/4000B2_912.jpg"),
    sound: require("./data/4000B2_moreover.mp3"),
  },
  {
    voc: "perspective",
    meaning: "viễn cảnh, triển vọng",
    image: require("./data/4000B2_913.jpg"),
    sound: require("./data/4000B2_perspective.mp3"),
  },
  {
    voc: "rational",
    meaning: "có lý, vừa phải, có chừng mực",
    image: require("./data/4000B2_914.jpg"),
    sound: require("./data/4000B2_rational.mp3"),
  },
  {
    voc: "recover",
    meaning: "lấy lại, giành lại, phục hồi, bình phục",
    image: require("./data/4000B2_915.jpg"),
    sound: require("./data/4000B2_recover.mp3"),
  },
  {
    voc: "rely; relied",
    meaning: "tin cậy, dựa vào",
    image: require("./data/4000B2_916.jpg"),
    sound: require("./data/4000B2_rely.mp3"),
  },
  {
    voc: "shock",
    meaning: "sốc",
    image: require("./data/4000B2_917.jpg"),
    sound: require("./data/4000B2_shock.mp3"),
  },
  {
    voc: "shy",
    meaning: "ngượng ngùng, nhút nhát, bẽn lẽn, e thẹn",
    image: require("./data/4000B2_918.jpg"),
    sound: require("./data/4000B2_shy.mp3"),
  },
  {
    voc: "stare",
    meaning: "nhìn chằm chằm",
    image: require("./data/4000B2_919.jpg"),
    sound: require("./data/4000B2_stare.mp3"),
  },
  {
    voc: "thus",
    meaning: "vì vậy, như vậy",
    image: require("./data/4000B2_920.jpg"),
    sound: require("./data/4000B2_thus.mp3"),
  },
  {
    voc: "aim",
    meaning: "mục đích, mục tiêu, ý định",
    image: require("./data/4000B2_921.jpg"),
    sound: require("./data/4000B2_aim.mp3"),
  },
  {
    voc: "attach",
    meaning: "đính kèm, gắn, dán",
    image: require("./data/4000B2_922.jpg"),
    sound: require("./data/4000B2_attach.mp3"),
  },
  {
    voc: "bet",
    meaning: "đánh cược",
    image: require("./data/4000B2_923.jpg"),
    sound: require("./data/4000B2_bet.mp3"),
  },
  {
    voc: "carriage",
    meaning: "xe ngựa,&nbsp;toa hành khách (đường sắt)",
    image: require("./data/4000B2_924.jpg"),
    sound: require("./data/4000B2_carriage.mp3"),
  },
  {
    voc: "classic",
    meaning: "kinh điển",
    image: require("./data/4000B2_925.jpg"),
    sound: require("./data/4000B2_classic.mp3"),
  },
  {
    voc: "commute",
    meaning: "đi lại đều đặn (giữa hai địa điểm)",
    image: require("./data/4000B2_926.jpg"),
    sound: require("./data/4000B2_commute.mp3"),
  },
  {
    voc: "confirm",
    meaning: "xác nhận; chứng thực",
    image: require("./data/4000B2_927.jpg"),
    sound: require("./data/4000B2_confirm.mp3"),
  },
  {
    voc: "criticize",
    meaning: "phê bình, phê phán, bình phẩm, chỉ trích",
    image: require("./data/4000B2_928.jpg"),
    sound: require("./data/4000B2_criticize.mp3"),
  },
  {
    voc: "differ",
    meaning: "khác, không giống",
    image: require("./data/4000B2_929.jpg"),
    sound: require("./data/4000B2_differ.mp3"),
  },
  {
    voc: "expense",
    meaning: "chi phí, phí tổn",
    image: require("./data/4000B2_930.jpg"),
    sound: require("./data/4000B2_expense.mp3"),
  },
  {
    voc: "formal",
    meaning: "trang trọng",
    image: require("./data/4000B2_931.jpg"),
    sound: require("./data/4000B2_formal.mp3"),
  },
  {
    voc: "height",
    meaning: "chiều cao, độ cao",
    image: require("./data/4000B2_932.jpg"),
    sound: require("./data/4000B2_height.mp3"),
  },
  {
    voc: "invent",
    meaning: "phát minh, sáng chế",
    image: require("./data/4000B2_933.jpg"),
    sound: require("./data/4000B2_invent.mp3"),
  },
  {
    voc: "junior",
    meaning: "ít thâm niên hơn; ở cấp dưới",
    image: require("./data/4000B2_934.jpg"),
    sound: require("./data/4000B2_junior.mp3"),
  },
  {
    voc: "labor",
    meaning: "lao động",
    image: require("./data/4000B2_935.jpg"),
    sound: require("./data/4000B2_labor.mp3"),
  },
  {
    voc: "mechanic",
    meaning: "thợ máy, công nhân cơ khí",
    image: require("./data/4000B2_936.jpg"),
    sound: require("./data/4000B2_mechanic.mp3"),
  },
  {
    voc: "prime",
    meaning: "nguyên nhân chính, thời kỳ đẹp nhất",
    image: require("./data/4000B2_937.jpg"),
    sound: require("./data/4000B2_prime.mp3"),
  },
  {
    voc: "shift",
    meaning: "đổi chỗ, dời chỗ, di chuyển",
    image: require("./data/4000B2_938.jpg"),
    sound: require("./data/4000B2_shift.mp3"),
  },
  {
    voc: "signal",
    meaning: "tín hiệu; hiệu lệnh",
    image: require("./data/4000B2_939.jpg"),
    sound: require("./data/4000B2_signal.mp3"),
  },
  {
    voc: "sincere",
    meaning: "thành thật, thật thà",
    image: require("./data/4000B2_940.jpg"),
    sound: require("./data/4000B2_sincere.mp3"),
  },
  {
    voc: "ability",
    meaning: "năng lực, khả năng",
    image: require("./data/4000B2_941.jpg"),
    sound: require("./data/4000B2_ability.mp3"),
  },
  {
    voc: "agriculture",
    meaning: "nông nghiệp",
    image: require("./data/4000B2_942.jpg"),
    sound: require("./data/4000B2_agriculture.mp3"),
  },
  {
    voc: "cartoon",
    meaning: "tranh đả kích, tranh biếm hoạ",
    image: require("./data/4000B2_943.jpg"),
    sound: require("./data/4000B2_cartoon.mp3"),
  },
  {
    voc: "ceiling",
    meaning: "trần (nhà...)",
    image: require("./data/4000B2_944.jpg"),
    sound: require("./data/4000B2_ceiling.mp3"),
  },
  {
    voc: "convince",
    meaning: "làm cho nghe theo, thuyết phục",
    image: require("./data/4000B2_945.jpg"),
    sound: require("./data/4000B2_convince.mp3"),
  },
  {
    voc: "curious",
    meaning: "tò mò, hiếu kỳ",
    image: require("./data/4000B2_946.jpg"),
    sound: require("./data/4000B2_curious.mp3"),
  },
  {
    voc: "delay",
    meaning: "trễ, hoãn",
    image: require("./data/4000B2_947.jpg"),
    sound: require("./data/4000B2_delay.mp3"),
  },
  {
    voc: "diary",
    meaning: "nhật ký",
    image: require("./data/4000B2_948.jpg"),
    sound: require("./data/4000B2_diary.mp3"),
  },
  {
    voc: "element",
    meaning: "yếu tố,&nbsp;nguyên tố",
    image: require("./data/4000B2_949.jpg"),
    sound: require("./data/4000B2_element.mp3"),
  },
  {
    voc: "faith",
    meaning: "niềm tin,&nbsp;sự trung thành",
    image: require("./data/4000B2_950.jpg"),
    sound: require("./data/4000B2_faith.mp3"),
  },
  {
    voc: "grain",
    meaning: "lương thực",
    image: require("./data/4000B2_951.jpg"),
    sound: require("./data/4000B2_grain.mp3"),
  },
  {
    voc: "greet",
    meaning: "chào mừng,&nbsp;đón chào",
    image: require("./data/4000B2_952.jpg"),
    sound: require("./data/4000B2_greet.mp3"),
  },
  {
    voc: "investigate",
    meaning: "điều tra, nghiên cứu",
    image: require("./data/4000B2_953.jpg"),
    sound: require("./data/4000B2_investigate.mp3"),
  },
  {
    voc: "joy",
    meaning: "niềm vui,&nbsp;sự hân hoan, sự vui sướng",
    image: require("./data/4000B2_954.jpg"),
    sound: require("./data/4000B2_joy.mp3"),
  },
  {
    voc: "label",
    meaning: "nhãn hàng hóa, nhãn hiệu",
    image: require("./data/4000B2_955.jpg"),
    sound: require("./data/4000B2_label.mp3"),
  },
  {
    voc: "monk",
    meaning: "thầy tu,&nbsp;nhà sư",
    image: require("./data/4000B2_956.jpg"),
    sound: require("./data/4000B2_monk.mp3"),
  },
  {
    voc: "odd",
    meaning: "kỳ cục, kỳ quặc, lẻ",
    image: require("./data/4000B2_957.jpg"),
    sound: require("./data/4000B2_odd.mp3"),
  },
  {
    voc: "pause",
    meaning: "tạm nghỉ, tạm ngừng",
    image: require("./data/4000B2_958.jpg"),
    sound: require("./data/4000B2_pause.mp3"),
  },
  {
    voc: "priest",
    meaning: "giáo sĩ, thầy tế",
    image: require("./data/4000B2_959.jpg"),
    sound: require("./data/4000B2_priest.mp3"),
  },
  {
    voc: "profession",
    meaning: "nghề, nghề nghiệp",
    image: require("./data/4000B2_960.jpg"),
    sound: require("./data/4000B2_profession.mp3"),
  },
  {
    voc: "adopt",
    meaning: "nhận làm con nuôi",
    image: require("./data/4000B2_961.jpg"),
    sound: require("./data/4000B2_adopt.mp3"),
  },
  {
    voc: "beg",
    meaning: "cầu xin,&nbsp;xin trân trọng (trong thư giao dịch)",
    image: require("./data/4000B2_962.jpg"),
    sound: require("./data/4000B2_beg.mp3"),
  },
  {
    voc: "beyond",
    meaning: "ở xa, ở phía bên kia",
    image: require("./data/4000B2_963.jpg"),
    sound: require("./data/4000B2_beyond.mp3"),
  },
  {
    voc: "costume",
    meaning: "quần áo / y phục (hóa trang, giả trang)",
    image: require("./data/4000B2_964.jpg"),
    sound: require("./data/4000B2_costume.mp3"),
  },
  {
    voc: "exclaim",
    meaning: "kêu lên, la lên (vì phấn khích)",
    image: require("./data/4000B2_965.jpg"),
    sound: require("./data/4000B2_exclaim.mp3"),
  },
  {
    voc: "extend",
    meaning: "kéo dài, mở rộng, vươn, đưa ra",
    image: require("./data/4000B2_966.jpg"),
    sound: require("./data/4000B2_extend.mp3"),
  },
  {
    voc: "fool",
    meaning: "ngu ngốc",
    image: require("./data/4000B2_967.jpg"),
    sound: require("./data/4000B2_fool.mp3"),
  },
  {
    voc: "forbid",
    meaning: "cấm, ngăn cấm",
    image: require("./data/4000B2_968.jpg"),
    sound: require("./data/4000B2_forbid.mp3"),
  },
  {
    voc: "illustrate",
    meaning: "minh hoạ, làm rõ ý",
    image: require("./data/4000B2_969.jpg"),
    sound: require("./data/4000B2_illustrate.mp3"),
  },
  {
    voc: "indeed",
    meaning: "thực vậy, quả thực",
    image: require("./data/4000B2_970.jpg"),
    sound: require("./data/4000B2_indeed.mp3"),
  },
  {
    voc: "interpret",
    meaning: "giải thích, làm sáng tỏ, làm phiên dịch",
    image: require("./data/4000B2_971.jpg"),
    sound: require("./data/4000B2_interpret.mp3"),
  },
  {
    voc: "kindly",
    meaning: "tử tế, tốt bụng",
    image: require("./data/4000B2_972.jpg"),
    sound: require("./data/4000B2_kindly.mp3"),
  },
  {
    voc: "motive",
    meaning:
      "noun:&nbsp;lý do, động cơ<div>adj:&nbsp;vận động, chuyển động</div>",
    image: require("./data/4000B2_973.jpg"),
    sound: require("./data/4000B2_motive.mp3"),
  },
  {
    voc: "nest",
    meaning: "tổ, ổ (chim, chuột...)",
    image: require("./data/4000B2_974.jpg"),
    sound: require("./data/4000B2_nest.mp3"),
  },
  {
    voc: "origin",
    meaning: "gốc, nguồn gốc",
    image: require("./data/4000B2_975.jpg"),
    sound: require("./data/4000B2_origin.mp3"),
  },
  {
    voc: "reception",
    meaning: "sự đón tiếp, sự tiếp tân, bữa tiệc chào mừng",
    image: require("./data/4000B2_976.jpg"),
    sound: require("./data/4000B2_reception.mp3"),
  },
  {
    voc: "reject",
    meaning: "từ chối, loại ra, bác bỏ",
    image: require("./data/4000B2_977.jpg"),
    sound: require("./data/4000B2_reject.mp3"),
  },
  {
    voc: "silence",
    meaning: "sự yên lặng, sự yên tĩnh, sự tĩnh mịch",
    image: require("./data/4000B2_978.jpg"),
    sound: require("./data/4000B2_silence.mp3"),
  },
  {
    voc: "stream",
    meaning: "dòng suối, dòng sông nhỏ",
    image: require("./data/4000B2_979.jpg"),
    sound: require("./data/4000B2_stream.mp3"),
  },
  {
    voc: "tone",
    meaning: "giọng, tông",
    image: require("./data/4000B2_980.jpg"),
    sound: require("./data/4000B2_tone.mp3"),
  },
  {
    voc: "accomplish",
    meaning: "hoàn thành, làm xong, đạt tới",
    image: require("./data/4000B2_981.jpg"),
    sound: require("./data/4000B2_accomplish.mp3"),
  },
  {
    voc: "approve",
    meaning: "tán thành, bằng lòng, chấp thuận<div>xác nhận, phê chuẩn</div>",
    image: require("./data/4000B2_982.jpg"),
    sound: require("./data/4000B2_approve.mp3"),
  },
  {
    voc: "approximate",
    meaning: "xấp xỉ, gần đúng",
    image: require("./data/4000B2_983.jpg"),
    sound: require("./data/4000B2_approximate.mp3"),
  },
  {
    voc: "barrier",
    meaning: "thanh chắn, hàng rào, ba ri e",
    image: require("./data/4000B2_984.jpg"),
    sound: require("./data/4000B2_barrier.mp3"),
  },
  {
    voc: "detect",
    meaning: "dò ra, tìm ra, phát hiện ra",
    image: require("./data/4000B2_985.jpg"),
    sound: require("./data/4000B2_detect.mp3"),
  },
  {
    voc: "duty",
    meaning: "bổn phận, nhiệm vụ, trách nhiệm",
    image: require("./data/4000B2_986.jpg"),
    sound: require("./data/4000B2_duty.mp3"),
  },
  {
    voc: "elementary",
    meaning: "cơ bản, cơ sở",
    image: require("./data/4000B2_987.jpg"),
    sound: require("./data/4000B2_elementary.mp3"),
  },
  {
    voc: "failure",
    meaning: "sự thất bại; sự hỏng; sự mất (mùa, điện...)",
    image: require("./data/4000B2_988.jpg"),
    sound: require("./data/4000B2_failure.mp3"),
  },
  {
    voc: "gradual",
    meaning: "dần dần, từ từ",
    image: require("./data/4000B2_989.jpg"),
    sound: require("./data/4000B2_gradual.mp3"),
  },
  {
    voc: "immigrant",
    meaning: "dân nhập cư",
    image: require("./data/4000B2_990.jpg"),
    sound: require("./data/4000B2_immigrant.mp3"),
  },
  {
    voc: "insert",
    meaning: "lồng vào, gài vào",
    image: require("./data/4000B2_991.jpg"),
    sound: require("./data/4000B2_insert.mp3"),
  },
  {
    voc: "instant",
    meaning: "chốc lát,&nbsp;ngay tức khắc",
    image: require("./data/4000B2_992.jpg"),
    sound: require("./data/4000B2_instant.mp3"),
  },
  {
    voc: "poverty",
    meaning: "sự nghèo đói",
    image: require("./data/4000B2_993.jpg"),
    sound: require("./data/4000B2_poverty.mp3"),
  },
  {
    voc: "pretend",
    meaning: "giả vờ, giả đò, giả bộ",
    image: require("./data/4000B2_994.jpg"),
    sound: require("./data/4000B2_pretend.mp3"),
  },
  {
    voc: "rank",
    meaning: "hạng, loại, cấp, bậc",
    image: require("./data/4000B2_995.jpg"),
    sound: require("./data/4000B2_rank.mp3"),
  },
  {
    voc: "recognition",
    meaning: "sự nhận ra,&nbsp;sự công nhận",
    image: require("./data/4000B2_996.jpg"),
    sound: require("./data/4000B2_recognition.mp3"),
  },
  {
    voc: "refrigerate",
    meaning: "làm lạnh; ướp lạnh",
    image: require("./data/4000B2_997.jpg"),
    sound: require("./data/4000B2_refrigerate.mp3"),
  },
  {
    voc: "rent",
    meaning: "tiền thuê (nhà, đất)",
    image: require("./data/4000B2_998.jpg"),
    sound: require("./data/4000B2_rent.mp3"),
  },
  {
    voc: "retire",
    meaning: "về hưu",
    image: require("./data/4000B2_999.jpg"),
    sound: require("./data/4000B2_retire.mp3"),
  },
  {
    voc: "statistic",
    meaning: "(bản, số liệu) thống kê&nbsp;",
    image: require("./data/4000B2_1000.jpg"),
    sound: require("./data/4000B2_statistic.mp3"),
  },
  {
    voc: "astronaut",
    meaning: "phi hành gia",
    image: require("./data/4000B2_1001.jpg"),
    sound: require("./data/4000B2_astronaut.mp3"),
  },
  {
    voc: "awake",
    meaning: "thức dậy.&nbsp;(nghĩa bóng) thức tỉnh",
    image: require("./data/4000B2_1002.jpg"),
    sound: require("./data/4000B2_awake.mp3"),
  },
  {
    voc: "courage",
    meaning: "sự can đảm, dũng khí",
    image: require("./data/4000B2_1003.jpg"),
    sound: require("./data/4000B2_courage.mp3"),
  },
  {
    voc: "float",
    meaning: "nổi, trôi lềnh bềnh",
    image: require("./data/4000B2_1004.jpg"),
    sound: require("./data/4000B2_float.mp3"),
  },
  {
    voc: "grant",
    meaning: "cho, ban (ơn), cấp",
    image: require("./data/4000B2_1005.jpg"),
    sound: require("./data/4000B2_grant.mp3"),
  },
  {
    voc: "gravity",
    meaning: "trọng lực; trọng lượng",
    image: require("./data/4000B2_1006.jpg"),
    sound: require("./data/4000B2_gravity.mp3"),
  },
  {
    voc: "jewel",
    meaning: "đá quý",
    image: require("./data/4000B2_1007.jpg"),
    sound: require("./data/4000B2_jewel.mp3"),
  },
  {
    voc: "miner",
    meaning: "thợ mỏ",
    image: require("./data/4000B2_1008.jpg"),
    sound: require("./data/4000B2_miner.mp3"),
  },
  {
    voc: "mineral",
    meaning: "khoáng vật, khoáng sản",
    image: require("./data/4000B2_1009.jpg"),
    sound: require("./data/4000B2_mineral.mp3"),
  },
  {
    voc: "participate",
    meaning: "tham gia, cùng góp phần",
    image: require("./data/4000B2_1010.jpg"),
    sound: require("./data/4000B2_participate.mp3"),
  },
  {
    voc: "permission",
    meaning: "sự cho phép,&nbsp;giấy phép",
    image: require("./data/4000B2_1011.jpg"),
    sound: require("./data/4000B2_permission.mp3"),
  },
  {
    voc: "pour",
    meaning: "rót, đổ, trút",
    image: require("./data/4000B2_1012.jpg"),
    sound: require("./data/4000B2_pour.mp3"),
  },
  {
    voc: "presence",
    meaning: "sự có mặt",
    image: require("./data/4000B2_1013.jpg"),
    sound: require("./data/4000B2_presence.mp3"),
  },
  {
    voc: "raw",
    meaning: "thô, sống",
    image: require("./data/4000B2_1014.jpg"),
    sound: require("./data/4000B2_raw.mp3"),
  },
  {
    voc: "satellite",
    meaning: "vệ tinh,&nbsp;chư hầu",
    image: require("./data/4000B2_1015.jpg"),
    sound: require("./data/4000B2_satellite.mp3"),
  },
  {
    voc: "scale",
    meaning: "tỷ lệ, quy mô, phạm vi",
    image: require("./data/4000B2_1016.jpg"),
    sound: require("./data/4000B2_scale.mp3"),
  },
  {
    voc: "skip",
    meaning: "bỏ qua, quên",
    image: require("./data/4000B2_1017.jpg"),
    sound: require("./data/4000B2_skip.mp3"),
  },
  {
    voc: "stretch",
    meaning: "kéo ra, căng ra, duỗi ra",
    image: require("./data/4000B2_1018.jpg"),
    sound: require("./data/4000B2_stretch.mp3"),
  },
  {
    voc: "telescope",
    meaning: "kính thiên văn",
    image: require("./data/4000B2_1019.jpg"),
    sound: require("./data/4000B2_telescope.mp3"),
  },
  {
    voc: "underground",
    meaning: "dưới đất, ngầm",
    image: require("./data/4000B2_1020.jpg"),
    sound: require("./data/4000B2_underground.mp3"),
  },
  {
    voc: "alarm",
    meaning: "sự báo động, sự báo nguy",
    image: require("./data/4000B2_1021.jpg"),
    sound: require("./data/4000B2_alarm.mp3"),
  },
  {
    voc: "apart",
    meaning: "riêng ra, xa ra",
    image: require("./data/4000B2_1022.jpg"),
    sound: require("./data/4000B2_apart.mp3"),
  },
  {
    voc: "arrest",
    meaning: "bắt giữ",
    image: require("./data/4000B2_1023.jpg"),
    sound: require("./data/4000B2_arrest.mp3"),
  },
  {
    voc: "award",
    meaning: "phần thưởng, giải thưởng",
    image: require("./data/4000B2_1024.jpg"),
    sound: require("./data/4000B2_award.mp3"),
  },
  {
    voc: "breed",
    meaning: "nòi, giống",
    image: require("./data/4000B2_1025.jpg"),
    sound: require("./data/4000B2_breed.mp3"),
  },
  {
    voc: "bucket",
    meaning: "thùng, xô",
    image: require("./data/4000B2_1026.jpg"),
    sound: require("./data/4000B2_bucket.mp3"),
  },
  {
    voc: "contest",
    meaning:
      "cuộc thi, trận đấu<div>đặt vấn đề nghi ngờ, không thừa nhận</div>",
    image: require("./data/4000B2_1027.jpg"),
    sound: require("./data/4000B2_contest.mp3"),
  },
  {
    voc: "convict",
    meaning: "kết án, tuyên bố có tội",
    image: require("./data/4000B2_1028.jpg"),
    sound: require("./data/4000B2_convict.mp3"),
  },
  {
    voc: "garage",
    meaning: "ga ra, nhà để ô tô, nơi chữa ô tô",
    image: require("./data/4000B2_1029.jpg"),
    sound: require("./data/4000B2_garage.mp3"),
  },
  {
    voc: "journalist",
    meaning: "nhà báo",
    image: require("./data/4000B2_1030.jpg"),
    sound: require("./data/4000B2_journalist.mp3"),
  },
  {
    voc: "pup",
    meaning: "chó con",
    image: require("./data/4000B2_1031.jpg"),
    sound: require("./data/4000B2_pup.mp3"),
  },
  {
    voc: "qualify",
    meaning: "đủ khả năng, đủ tiêu chuẩn, đủ tư cách",
    image: require("./data/4000B2_1032.jpg"),
    sound: require("./data/4000B2_qualify.mp3"),
  },
  {
    voc: "repair",
    meaning: "sửa chữa",
    image: require("./data/4000B2_1033.jpg"),
    sound: require("./data/4000B2_repair.mp3"),
  },
  {
    voc: "resume",
    meaning: "lấy lại, hồi phục lại,&nbsp;lại tiếp tục (sau khi nghỉ, dừng)",
    image: require("./data/4000B2_1034.jpg"),
    sound: require("./data/4000B2_resume.mp3"),
  },
  {
    voc: "rob",
    meaning: "cướp, cướp đoạt",
    image: require("./data/4000B2_1035.jpg"),
    sound: require("./data/4000B2_rob.mp3"),
  },
  {
    voc: "slip",
    meaning: "trượt; trượt ngã",
    image: require("./data/4000B2_1036.jpg"),
    sound: require("./data/4000B2_slip.mp3"),
  },
  {
    voc: "somewhat",
    meaning: "hơi, gọi là, một chút",
    image: require("./data/4000B2_1037.jpg"),
    sound: require("./data/4000B2_somewhat.mp3"),
  },
  {
    voc: "stable",
    meaning: "vững vàng; ổn định",
    image: require("./data/4000B2_1038.jpg"),
    sound: require("./data/4000B2_stable.mp3"),
  },
  {
    voc: "tissue",
    meaning: "giấy vệ sinh, giấy lụa, vải mỏng",
    image: require("./data/4000B2_1039.jpg"),
    sound: require("./data/4000B2_tissue.mp3"),
  },
  {
    voc: "yard",
    meaning: "sân (có rào xung quanh)",
    image: require("./data/4000B2_1040.jpg"),
    sound: require("./data/4000B2_yard.mp3"),
  },
  {
    voc: "alike",
    meaning: "giống nhau,&nbsp;tương tự",
    image: require("./data/4000B2_1041.jpg"),
    sound: require("./data/4000B2_alike.mp3"),
  },
  {
    voc: "annoy",
    meaning: "làm khó chịu,&nbsp;làm phiền, quấy rầy",
    image: require("./data/4000B2_1042.jpg"),
    sound: require("./data/4000B2_annoy.mp3"),
  },
  {
    voc: "architecture",
    meaning: "kiểu kiến trúc",
    image: require("./data/4000B2_1043.jpg"),
    sound: require("./data/4000B2_architecture.mp3"),
  },
  {
    voc: "artificial",
    meaning: "nhân tạo",
    image: require("./data/4000B2_1044.jpg"),
    sound: require("./data/4000B2_artificial.mp3"),
  },
  {
    voc: "chain",
    meaning: "dây, xích",
    image: require("./data/4000B2_1045.jpg"),
    sound: require("./data/4000B2_chain.mp3"),
  },
  {
    voc: "distinct",
    meaning: "riêng biệt; khác biệt",
    image: require("./data/4000B2_1046.jpg"),
    sound: require("./data/4000B2_distinct.mp3"),
  },
  {
    voc: "distinguish",
    meaning: "phân biệt, nhận ra",
    image: require("./data/4000B2_1047.jpg"),
    sound: require("./data/4000B2_distinguish.mp3"),
  },
  {
    voc: "dust",
    meaning: "bụi",
    image: require("./data/4000B2_1048.jpg"),
    sound: require("./data/4000B2_dust.mp3"),
  },
  {
    voc: "excitement",
    meaning: "sự phấn khích",
    image: require("./data/4000B2_1049.jpg"),
    sound: require("./data/4000B2_excitement.mp3"),
  },
  {
    voc: "heal",
    meaning:
      "chữa khỏi (bệnh...), làm lành (vết thương...),&nbsp;hàn gắn (mối quan hệ bị nứt rạn)",
    image: require("./data/4000B2_1050.jpg"),
    sound: require("./data/4000B2_heal.mp3"),
  },
  {
    voc: "inherit",
    meaning: "thừa hưởng, thừa kế",
    image: require("./data/4000B2_1051.jpg"),
    sound: require("./data/4000B2_inherit.mp3"),
  },
  {
    voc: "manner",
    meaning: "cách, lối, kiểu",
    image: require("./data/4000B2_1052.jpg"),
    sound: require("./data/4000B2_manner.mp3"),
  },
  {
    voc: "mount",
    meaning: "tăng lên,&nbsp;trèo, leo",
    image: require("./data/4000B2_1053.jpg"),
    sound: require("./data/4000B2_mount.mp3"),
  },
  {
    voc: "roof",
    meaning: "mái nhà, nóc",
    image: require("./data/4000B2_1054.jpg"),
    sound: require("./data/4000B2_roof.mp3"),
  },
  {
    voc: "shortage",
    meaning: "sự thiếu; số lượng thiếu",
    image: require("./data/4000B2_1055.jpg"),
    sound: require("./data/4000B2_shortage.mp3"),
  },
  {
    voc: "solid",
    meaning: "đặc, vững chắc, rắn chắc",
    image: require("./data/4000B2_1056.jpg"),
    sound: require("./data/4000B2_solid.mp3"),
  },
  {
    voc: "stock",
    meaning: "cổ phiếu, dự trữ",
    image: require("./data/4000B2_1057.jpg"),
    sound: require("./data/4000B2_stock.mp3"),
  },
  {
    voc: "substance",
    meaning: "chất, vật chất",
    image: require("./data/4000B2_1058.jpg"),
    sound: require("./data/4000B2_substance.mp3"),
  },
  {
    voc: "tomb",
    meaning: "mộ",
    image: require("./data/4000B2_1059.jpg"),
    sound: require("./data/4000B2_tomb.mp3"),
  },
  {
    voc: "wound",
    meaning: "vết thương, thương tích",
    image: require("./data/4000B2_1060.jpg"),
    sound: require("./data/4000B2_wound.mp3"),
  },
  {
    voc: "bath",
    meaning: "sự tắm,&nbsp;chậu tắm, bồn tắm",
    image: require("./data/4000B2_1061.jpg"),
    sound: require("./data/4000B2_bath.mp3"),
  },
  {
    voc: "bend",
    meaning: "bẻ cong, uốn cong",
    image: require("./data/4000B2_1062.jpg"),
    sound: require("./data/4000B2_bend.mp3"),
  },
  {
    voc: "chew",
    meaning: "nhai",
    image: require("./data/4000B2_1063.jpg"),
    sound: require("./data/4000B2_chew.mp3"),
  },
  {
    voc: "disabled",
    meaning: "tàn tật",
    image: require("./data/4000B2_1064.jpg"),
    sound: require("./data/4000B2_disabled.mp3"),
  },
  {
    voc: "fantastic",
    meaning: "siêu tốt, lập dị, vô cùng to lớn",
    image: require("./data/4000B2_1065.jpg"),
    sound: require("./data/4000B2_fantastic.mp3"),
  },
  {
    voc: "fiction",
    meaning: "tiểu thuyết",
    image: require("./data/4000B2_1066.jpg"),
    sound: require("./data/4000B2_fiction.mp3"),
  },
  {
    voc: "flag",
    meaning: "lá cờ",
    image: require("./data/4000B2_1067.jpg"),
    sound: require("./data/4000B2_flag.mp3"),
  },
  {
    voc: "inspect",
    meaning: "xem xét kỹ, kiểm tra",
    image: require("./data/4000B2_1068.jpg"),
    sound: require("./data/4000B2_inspect.mp3"),
  },
  {
    voc: "journal",
    meaning: "tạp chí chuyên ngành",
    image: require("./data/4000B2_1069.jpg"),
    sound: require("./data/4000B2_journal.mp3"),
  },
  {
    voc: "liquid",
    meaning: "chất lỏng",
    image: require("./data/4000B2_1070.jpg"),
    sound: require("./data/4000B2_liquid.mp3"),
  },
  {
    voc: "marvel",
    meaning: "ngạc nhiên, kinh ngạc",
    image: require("./data/4000B2_1071.jpg"),
    sound: require("./data/4000B2_marvel.mp3"),
  },
  {
    voc: "nutrient",
    meaning: "chất dinh dưỡng",
    image: require("./data/4000B2_1072.jpg"),
    sound: require("./data/4000B2_nutrient.mp3"),
  },
  {
    voc: "overcome; overcame",
    meaning: "vượt qua, khắc phục (khó khăn...)",
    image: require("./data/4000B2_1073.jpg"),
    sound: require("./data/4000B2_overcome.mp3"),
  },
  {
    voc: "recall",
    meaning: "nhớ lại",
    image: require("./data/4000B2_1074.jpg"),
    sound: require("./data/4000B2_recall.mp3"),
  },
  {
    voc: "regret",
    meaning: "hối tiếc",
    image: require("./data/4000B2_1075.jpg"),
    sound: require("./data/4000B2_regret.mp3"),
  },
  {
    voc: "soul",
    meaning: "tâm hồn",
    image: require("./data/4000B2_1076.jpg"),
    sound: require("./data/4000B2_soul.mp3"),
  },
  {
    voc: "sufficient",
    meaning: "đủ",
    image: require("./data/4000B2_1077.jpg"),
    sound: require("./data/4000B2_sufficient.mp3"),
  },
  {
    voc: "surgery",
    meaning: "ca phẫu thuật",
    image: require("./data/4000B2_1078.jpg"),
    sound: require("./data/4000B2_surgery.mp3"),
  },
  {
    voc: "tough",
    meaning: "khó, hóc búa",
    image: require("./data/4000B2_1079.jpg"),
    sound: require("./data/4000B2_tough.mp3"),
  },
  {
    voc: "tube",
    meaning: "ống, săm",
    image: require("./data/4000B2_1080.jpg"),
    sound: require("./data/4000B2_tube.mp3"),
  },
  {
    voc: "admit",
    meaning: "thừa nhận, thú nhận,&nbsp;cho vào",
    image: require("./data/4000B2_1081.jpg"),
    sound: require("./data/4000B2_admit.mp3"),
  },
  {
    voc: "bin",
    meaning: "thùng",
    image: require("./data/4000B2_1082.jpg"),
    sound: require("./data/4000B2_bin.mp3"),
  },
  {
    voc: "bowl",
    meaning: "cái bát, cái tô",
    image: require("./data/4000B2_1083.jpg"),
    sound: require("./data/4000B2_bowl.mp3"),
  },
  {
    voc: "cabin",
    meaning: "nhà gỗ nhỏ, túp lều",
    image: require("./data/4000B2_1084.jpg"),
    sound: require("./data/4000B2_cabin.mp3"),
  },
  {
    voc: "cash",
    meaning: "tiền, tiền mặt",
    image: require("./data/4000B2_1085.jpg"),
    sound: require("./data/4000B2_cash.mp3"),
  },
  {
    voc: "criminal",
    meaning: "kẻ phạm tội, tội phạm",
    image: require("./data/4000B2_1086.jpg"),
    sound: require("./data/4000B2_criminal.mp3"),
  },
  {
    voc: "dozen",
    meaning: "một tá (mười hai)",
    image: require("./data/4000B2_1087.jpg"),
    sound: require("./data/4000B2_dozen.mp3"),
  },
  {
    voc: "elder",
    meaning: "người nhiều tuổi hơn",
    image: require("./data/4000B2_1088.jpg"),
    sound: require("./data/4000B2_elder.mp3"),
  },
  {
    voc: "facial",
    meaning: "(thuộc) mặt",
    image: require("./data/4000B2_1089.jpg"),
    sound: require("./data/4000B2_facial.mp3"),
  },
  {
    voc: "fence",
    meaning: "hàng rào",
    image: require("./data/4000B2_1090.jpg"),
    sound: require("./data/4000B2_fence.mp3"),
  },
  {
    voc: "inspire",
    meaning: "truyền cảm hứng",
    image: require("./data/4000B2_1091.jpg"),
    sound: require("./data/4000B2_inspire.mp3"),
  },
  {
    voc: "mere",
    meaning: "chỉ là, suýt soát",
    image: require("./data/4000B2_1092.jpg"),
    sound: require("./data/4000B2_mere.mp3"),
  },
  {
    voc: "neat",
    meaning: "gọn gàng, ngăn nắp",
    image: require("./data/4000B2_1093.jpg"),
    sound: require("./data/4000B2_neat.mp3"),
  },
  {
    voc: "occasion",
    meaning: "dịp, cơ hội",
    image: require("./data/4000B2_1094.jpg"),
    sound: require("./data/4000B2_occasion.mp3"),
  },
  {
    voc: "penalty",
    meaning: "hình phạt, tiền phạt",
    image: require("./data/4000B2_1095.jpg"),
    sound: require("./data/4000B2_penalty.mp3"),
  },
  {
    voc: "rude",
    meaning: "khiếm nhã, bất lịch sự, vô lễ",
    image: require("./data/4000B2_1096.jpg"),
    sound: require("./data/4000B2_rude.mp3"),
  },
  {
    voc: "settle",
    meaning: "giải quyết,&nbsp;dàn xếp, hoà giải",
    image: require("./data/4000B2_1097.jpg"),
    sound: require("./data/4000B2_settle.mp3"),
  },
  {
    voc: "vehicle",
    meaning: "xe cộ",
    image: require("./data/4000B2_1098.jpg"),
    sound: require("./data/4000B2_vehicle.mp3"),
  },
  {
    voc: "wallet",
    meaning: "cái ví (đựng tiền)",
    image: require("./data/4000B2_1099.jpg"),
    sound: require("./data/4000B2_wallet.mp3"),
  },
  {
    voc: "yell",
    meaning: "la hét, quát tháo",
    image: require("./data/4000B2_1100.jpg"),
    sound: require("./data/4000B2_yell.mp3"),
  },
  {
    voc: "accuse",
    meaning: "buộc tội, kết tội; tố cáo",
    image: require("./data/4000B2_1101.jpg"),
    sound: require("./data/4000B2_accuse.mp3"),
  },
  {
    voc: "adjust",
    meaning: "điều chỉnh",
    image: require("./data/4000B2_1102.jpg"),
    sound: require("./data/4000B2_adjust.mp3"),
  },
  {
    voc: "amuse",
    meaning: "làm vui, làm thích thú, làm buồn cười",
    image: require("./data/4000B2_1103.jpg"),
    sound: require("./data/4000B2_amuse.mp3"),
  },
  {
    voc: "coral",
    meaning: "san hô",
    image: require("./data/4000B2_1104.jpg"),
    sound: require("./data/4000B2_coral.mp3"),
  },
  {
    voc: "cotton",
    meaning: "bông, cô tông",
    image: require("./data/4000B2_1105.jpg"),
    sound: require("./data/4000B2_cotton.mp3"),
  },
  {
    voc: "crash",
    meaning: "đâm, va chạm",
    image: require("./data/4000B2_1106.jpg"),
    sound: require("./data/4000B2_crash.mp3"),
  },
  {
    voc: "deck",
    meaning: "boong tàu, sàn tàu",
    image: require("./data/4000B2_1107.jpg"),
    sound: require("./data/4000B2_deck.mp3"),
  },
  {
    voc: "engage",
    meaning: "làm, tiến hành,&nbsp;hứa hẹn,cam kết, hứa hôn",
    image: require("./data/4000B2_1108.jpg"),
    sound: require("./data/4000B2_engage.mp3"),
  },
  {
    voc: "firm",
    meaning: "vững chắc; bền vững;&nbsp;hãng, công ty",
    image: require("./data/4000B2_1109.jpg"),
    sound: require("./data/4000B2_firm.mp3"),
  },
  {
    voc: "fuel",
    meaning: "chất đốt, nhiên liệu",
    image: require("./data/4000B2_1110.jpg"),
    sound: require("./data/4000B2_fuel.mp3"),
  },
  {
    voc: "grand",
    meaning: "hùng vĩ, rất lớn",
    image: require("./data/4000B2_1111.jpg"),
    sound: require("./data/4000B2_grand.mp3"),
  },
  {
    voc: "hurricane",
    meaning: "cơn bão tố",
    image: require("./data/4000B2_1112.jpg"),
    sound: require("./data/4000B2_hurricane.mp3"),
  },
  {
    voc: "loss",
    meaning: "sự mất,&nbsp;sự thiệt hại, sự thua",
    image: require("./data/4000B2_1113.jpg"),
    sound: require("./data/4000B2_loss.mp3"),
  },
  {
    voc: "plain",
    meaning: "đơn giản, mộc mạc, trơn, một màu",
    image: require("./data/4000B2_1114.jpg"),
    sound: require("./data/4000B2_plain.mp3"),
  },
  {
    voc: "reef",
    meaning: "đá ngầm, rạn đá cạnh biển",
    image: require("./data/4000B2_1115.jpg"),
    sound: require("./data/4000B2_reef.mp3"),
  },
  {
    voc: "shut",
    meaning: "đóng, khép",
    image: require("./data/4000B2_1116.jpg"),
    sound: require("./data/4000B2_shut.mp3"),
  },
  {
    voc: "strict",
    meaning: "nghiêm ngặt, nghiêm khắc",
    image: require("./data/4000B2_1117.jpg"),
    sound: require("./data/4000B2_strict.mp3"),
  },
  {
    voc: "surf",
    meaning: "lướt sóng",
    image: require("./data/4000B2_1118.jpg"),
    sound: require("./data/4000B2_surf.mp3"),
  },
  {
    voc: "task",
    meaning: "nhiệm vụ, phận sự",
    image: require("./data/4000B2_1119.jpg"),
    sound: require("./data/4000B2_task2.mp3"),
  },
  {
    voc: "zone",
    meaning: "khu vực, vùng",
    image: require("./data/4000B2_1120.jpg"),
    sound: require("./data/4000B2_zone.mp3"),
  },
  {
    voc: "apology",
    meaning: "xin lỗi, sự xin lỗi",
    image: require("./data/4000B2_1121.jpg"),
    sound: require("./data/4000B2_apology.mp3"),
  },
  {
    voc: "bold",
    meaning: "dũng cảm, táo bạo",
    image: require("./data/4000B2_1122.jpg"),
    sound: require("./data/4000B2_bold.mp3"),
  },
  {
    voc: "capture",
    meaning: "bắt giữ, bắt,&nbsp;lấy được, giành được",
    image: require("./data/4000B2_1123.jpg"),
    sound: require("./data/4000B2_capture.mp3"),
  },
  {
    voc: "cardinal",
    meaning: "chính, chủ yếu, cốt yếu",
    image: require("./data/4000B2_1124.jpg"),
    sound: require("./data/4000B2_cardinal.mp3"),
  },
  {
    voc: "duke",
    meaning: "công tước",
    image: require("./data/4000B2_1125.jpg"),
    sound: require("./data/4000B2_duke.mp3"),
  },
  {
    voc: "expose",
    meaning: "phơi bày, phô ra",
    image: require("./data/4000B2_1126.jpg"),
    sound: require("./data/4000B2_expose.mp3"),
  },
  {
    voc: "guilty",
    meaning: "có lỗi, có tội",
    image: require("./data/4000B2_1127.jpg"),
    sound: require("./data/4000B2_guilty.mp3"),
  },
  {
    voc: "hire",
    meaning: "mướn, thuê (nhân công),&nbsp;cho thuê (nhà...)",
    image: require("./data/4000B2_1128.jpg"),
    sound: require("./data/4000B2_hire.mp3"),
  },
  {
    voc: "innocent",
    meaning: "vô tội; không có tội",
    image: require("./data/4000B2_1129.jpg"),
    sound: require("./data/4000B2_innocent.mp3"),
  },
  {
    voc: "jail",
    meaning: "nhà tù",
    image: require("./data/4000B2_1130.jpg"),
    sound: require("./data/4000B2_jail.mp3"),
  },
  {
    voc: "minister",
    meaning: "bộ trưởng",
    image: require("./data/4000B2_1131.jpg"),
    sound: require("./data/4000B2_minister.mp3"),
  },
  {
    voc: "ordinary",
    meaning: "thông thường, bình thường",
    image: require("./data/4000B2_1132.jpg"),
    sound: require("./data/4000B2_ordinary.mp3"),
  },
  {
    voc: "permanent",
    meaning: "lâu bền, vĩnh cửu,&nbsp;lâu dài",
    image: require("./data/4000B2_1133.jpg"),
    sound: require("./data/4000B2_permanent.mp3"),
  },
  {
    voc: "preserve",
    meaning: "giữ gìn, bảo quản, bảo tồn, duy trì",
    image: require("./data/4000B2_1134.jpg"),
    sound: require("./data/4000B2_preserve.mp3"),
  },
  {
    voc: "pronounce; pronouncing",
    meaning: "phát âm,&nbsp;tuyên bố",
    image: require("./data/4000B2_1135.jpg"),
    sound: require("./data/4000B2_pronounce.mp3"),
  },
  {
    voc: "resemble",
    meaning: "giống với&nbsp;(người nào, vật gì)",
    image: require("./data/4000B2_1136.jpg"),
    sound: require("./data/4000B2_resemble.mp3"),
  },
  {
    voc: "symptom",
    meaning: "triệu chứng",
    image: require("./data/4000B2_1137.jpg"),
    sound: require("./data/4000B2_symptom.mp3"),
  },
  {
    voc: "tobacco",
    meaning: "thuốc lá",
    image: require("./data/4000B2_1138.jpg"),
    sound: require("./data/4000B2_tobacco.mp3"),
  },
  {
    voc: "twin",
    meaning: "sinh đôi",
    image: require("./data/4000B2_1139.jpg"),
    sound: require("./data/4000B2_twin.mp3"),
  },
  {
    voc: "witch",
    meaning: "mụ phù thuỷ,&nbsp;người đàn bà quyến rũ",
    image: require("./data/4000B2_1140.jpg"),
    sound: require("./data/4000B2_witch.mp3"),
  },
  {
    voc: "accompany",
    meaning: "đi theo, đi cùng",
    image: require("./data/4000B2_1141.jpg"),
    sound: require("./data/4000B2_accompany.mp3"),
  },
  {
    voc: "bare",
    meaning: "trần, trọc, trống không",
    image: require("./data/4000B2_1142.jpg"),
    sound: require("./data/4000B2_bare.mp3"),
  },
  {
    voc: "branch",
    meaning:
      "cành cây,&nbsp;nhánh (sông),&nbsp;chi nhánh (ngân hàng, công ty...)",
    image: require("./data/4000B2_1143.jpg"),
    sound: require("./data/4000B2_branch.mp3"),
  },
  {
    voc: "breath",
    meaning: "hơi thở, sự thở",
    image: require("./data/4000B2_1144.jpg"),
    sound: require("./data/4000B2_breath.mp3"),
  },
  {
    voc: "bridge",
    meaning: "cây cầu",
    image: require("./data/4000B2_1145.jpg"),
    sound: require("./data/4000B2_bridge.mp3"),
  },
  {
    voc: "cast",
    meaning:
      "quăng, ném, liệng, thả,<div>đúc, nấu chảy, đổ khuôn (để đúc)</div>",
    image: require("./data/4000B2_1146.jpg"),
    sound: require("./data/4000B2_cast.mp3"),
  },
  {
    voc: "dare",
    meaning: "dám, thách, dám đương đầu với",
    image: require("./data/4000B2_1147.jpg"),
    sound: require("./data/4000B2_dare.mp3"),
  },
  {
    voc: "electronic",
    meaning: "(thuộc) điện tử",
    image: require("./data/4000B2_1148.jpg"),
    sound: require("./data/4000B2_electronic.mp3"),
  },
  {
    voc: "inn",
    meaning: "quán trọ, khách sạn nhỏ (ở nông thôn, thị trấn)",
    image: require("./data/4000B2_1149.jpg"),
    sound: require("./data/4000B2_inn.mp3"),
  },
  {
    voc: "net",
    meaning:
      "lưới, mạng (tóc, nhện...)<div>thực trả, thực lĩnh (sau khi trừ hết chi phí)</div>",
    image: require("./data/4000B2_1150.jpg"),
    sound: require("./data/4000B2_net.mp3"),
  },
  {
    voc: "philosophy",
    meaning: "triết học, triết lý",
    image: require("./data/4000B2_1151.jpg"),
    sound: require("./data/4000B2_philosophy.mp3"),
  },
  {
    voc: "pot",
    meaning: "nồi, ấm, bình, lọ, chậu, hũ",
    image: require("./data/4000B2_1152.jpg"),
    sound: require("./data/4000B2_pot.mp3"),
  },
  {
    voc: "seed",
    meaning: "hạt giống",
    image: require("./data/4000B2_1153.jpg"),
    sound: require("./data/4000B2_seed.mp3"),
  },
  {
    voc: "sharp",
    meaning: "sắc, nhọn, bén",
    image: require("./data/4000B2_1154.jpg"),
    sound: require("./data/4000B2_sharp.mp3"),
  },
  {
    voc: "sort",
    meaning: "thứ, loại, hạng",
    image: require("./data/4000B2_1155.jpg"),
    sound: require("./data/4000B2_sort.mp3"),
  },
  {
    voc: "subtract",
    meaning: "(toán học) trừ",
    image: require("./data/4000B2_1156.jpg"),
    sound: require("./data/4000B2_subtract.mp3"),
  },
  {
    voc: "tight",
    meaning: "chặt, khít",
    image: require("./data/4000B2_1157.jpg"),
    sound: require("./data/4000B2_tight.mp3"),
  },
  {
    voc: "virtual",
    meaning: "thực sự, thực tế;&nbsp;(vật lý) ảo",
    image: require("./data/4000B2_1158.jpg"),
    sound: require("./data/4000B2_virtual.mp3"),
  },
  {
    voc: "weigh",
    meaning: "cân,&nbsp;cân nhấc,&nbsp;nhấc xem nặng nhẹ",
    image: require("./data/4000B2_1159.jpg"),
    sound: require("./data/4000B2_weigh.mp3"),
  },
  {
    voc: "whisper",
    meaning: "nói thầm; xì xào",
    image: require("./data/4000B2_1160.jpg"),
    sound: require("./data/4000B2_whisper.mp3"),
  },
  {
    voc: "abstract",
    meaning:
      "trừu tượng,&nbsp;bản tóm tắt (cuốn sách, luận án, bài diễn văn...)",
    image: require("./data/4000B2_1161.jpg"),
    sound: require("./data/4000B2_abstract.mp3"),
  },
  {
    voc: "annual",
    meaning: "hàng năm",
    image: require("./data/4000B2_1162.jpg"),
    sound: require("./data/4000B2_annual.mp3"),
  },
  {
    voc: "clay",
    meaning: "đất sét",
    image: require("./data/4000B2_1163.jpg"),
    sound: require("./data/4000B2_clay.mp3"),
  },
  {
    voc: "cloth",
    meaning: "vải,&nbsp;khăn lau; khăn trải (bàn)",
    image: require("./data/4000B2_1164.jpg"),
    sound: require("./data/4000B2_cloth.mp3"),
  },
  {
    voc: "curtain",
    meaning: "rèm, màn cửa,&nbsp;màn (ở rạp hát),&nbsp;màn (khói, sương)",
    image: require("./data/4000B2_1165.jpg"),
    sound: require("./data/4000B2_curtain.mp3"),
  },
  {
    voc: "deserve",
    meaning: "xứng đáng",
    image: require("./data/4000B2_1166.jpg"),
    sound: require("./data/4000B2_deserve.mp3"),
  },
  {
    voc: "feather",
    meaning: "lông (chim)",
    image: require("./data/4000B2_1167.jpg"),
    sound: require("./data/4000B2_feather.mp3"),
  },
  {
    voc: "fertile",
    meaning: "tốt, màu mỡ (đất)",
    image: require("./data/4000B2_1168.jpg"),
    sound: require("./data/4000B2_fertile.mp3"),
  },
  {
    voc: "flood",
    meaning: "lũ, lụt, ngập",
    image: require("./data/4000B2_1169.jpg"),
    sound: require("./data/4000B2_flood.mp3"),
  },
  {
    voc: "furniture",
    meaning: "đồ nội thất, đồ đạc (trong nhà)",
    image: require("./data/4000B2_1170.jpg"),
    sound: require("./data/4000B2_furniture.mp3"),
  },
  {
    voc: "grave",
    meaning: "mộ, phần mộ",
    image: require("./data/4000B2_1171.jpg"),
    sound: require("./data/4000B2_grave.mp3"),
  },
  {
    voc: "ideal",
    meaning: "lý tưởng",
    image: require("./data/4000B2_1172.jpg"),
    sound: require("./data/4000B2_ideal.mp3"),
  },
  {
    voc: "intelligence",
    meaning: "trí thông minh,&nbsp;sự hiểu biết,&nbsp;cơ quan tình báo",
    image: require("./data/4000B2_1173.jpg"),
    sound: require("./data/4000B2_intelligence.mp3"),
  },
  {
    voc: "nowadays",
    meaning: "ngày nay,&nbsp;thời buổi này",
    image: require("./data/4000B2_1174.jpg"),
    sound: require("./data/4000B2_nowadays.mp3"),
  },
  {
    voc: "obtain",
    meaning: "đạt được, giành được, kiếm được",
    image: require("./data/4000B2_1175.jpg"),
    sound: require("./data/4000B2_obtain.mp3"),
  },
  {
    voc: "religious",
    meaning: "(thuộc) tôn giáo",
    image: require("./data/4000B2_1176.jpg"),
    sound: require("./data/4000B2_religious.mp3"),
  },
  {
    voc: "romantic",
    meaning: "lãng mạng",
    image: require("./data/4000B2_1177.jpg"),
    sound: require("./data/4000B2_romantic.mp3"),
  },
  {
    voc: "shell",
    meaning: "vỏ, mai",
    image: require("./data/4000B2_1178.jpg"),
    sound: require("./data/4000B2_shell.mp3"),
  },
  {
    voc: "shore",
    meaning: "bờ (biển, hồ lớn)",
    image: require("./data/4000B2_1179.jpg"),
    sound: require("./data/4000B2_shore.mp3"),
  },
  {
    voc: "wheel",
    meaning: "bánh (xe)",
    image: require("./data/4000B2_1180.jpg"),
    sound: require("./data/4000B2_wheel.mp3"),
  },
  {
    voc: "appeal",
    meaning: "hấp dẫn, lôi cuốn",
    image: require("./data/4000B2_1181.jpg"),
    sound: require("./data/4000B2_appeal.mp3"),
  },
  {
    voc: "assume",
    meaning: "cho rằng (là đúng); giả sử (là đúng)",
    image: require("./data/4000B2_1182.jpg"),
    sound: require("./data/4000B2_assume.mp3"),
  },
  {
    voc: "borrow",
    meaning: "mượn, vay",
    image: require("./data/4000B2_1183.jpg"),
    sound: require("./data/4000B2_borrow.mp3"),
  },
  {
    voc: "client",
    meaning: "khách hàng (sử dụng dịch vụ)",
    image: require("./data/4000B2_1184.jpg"),
    sound: require("./data/4000B2_client.mp3"),
  },
  {
    voc: "downtown",
    meaning: "khu trung tâm, khu buôn bán kinh doanh (của một thành phố)",
    image: require("./data/4000B2_1185.jpg"),
    sound: require("./data/4000B2_downtown.mp3"),
  },
  {
    voc: "dull",
    meaning: "đều đều, buồn tẻ,&nbsp;uể oải, chậm chạp",
    image: require("./data/4000B2_1186.jpg"),
    sound: require("./data/4000B2_dull.mp3"),
  },
  {
    voc: "embarrass",
    meaning:
      "làm lúng túng, làm ngượng nghịu,&nbsp;gây khó khăn về kinh tế cho",
    image: require("./data/4000B2_1187.jpg"),
    sound: require("./data/4000B2_embarrass.mp3"),
  },
  {
    voc: "fare",
    meaning: "tiền vé (tàu, xe, máy bay...)",
    image: require("./data/4000B2_1188.jpg"),
    sound: require("./data/4000B2_fare.mp3"),
  },
  {
    voc: "former",
    meaning: "cũ, xưa,&nbsp;trước kia",
    image: require("./data/4000B2_1189.jpg"),
    sound: require("./data/4000B2_former.mp3"),
  },
  {
    voc: "formula",
    meaning: "công thức (toán học)",
    image: require("./data/4000B2_1190.jpg"),
    sound: require("./data/4000B2_formula.mp3"),
  },
  {
    voc: "found",
    meaning: "sáng lập, đặt nền móng",
    image: require("./data/4000B2_1191.jpg"),
    sound: require("./data/4000B2_found.mp3"),
  },
  {
    voc: "invest",
    meaning: "đầu tư",
    image: require("./data/4000B2_1192.jpg"),
    sound: require("./data/4000B2_invest.mp3"),
  },
  {
    voc: "loan",
    meaning: "khoản vay, sự vay nợ",
    image: require("./data/4000B2_1193.jpg"),
    sound: require("./data/4000B2_loan.mp3"),
  },
  {
    voc: "practical",
    meaning: "thực tế, thực dụng; có ích",
    image: require("./data/4000B2_1194.jpg"),
    sound: require("./data/4000B2_practical.mp3"),
  },
  {
    voc: "quarter",
    meaning: "một phần tư đô la (25 cent), giờ (15'), năm (một quý trong năm)",
    image: require("./data/4000B2_1195.jpg"),
    sound: require("./data/4000B2_quarter.mp3"),
  },
  {
    voc: "salary",
    meaning: "tiền lương",
    image: require("./data/4000B2_1196.jpg"),
    sound: require("./data/4000B2_salary.mp3"),
  },
  {
    voc: "scholarship",
    meaning: "học bổng",
    image: require("./data/4000B2_1197.jpg"),
    sound: require("./data/4000B2_scholarship.mp3"),
  },
  {
    voc: "temporary",
    meaning: "tạm thời, nhất thời, lâm thời",
    image: require("./data/4000B2_1198.jpg"),
    sound: require("./data/4000B2_temporary.mp3"),
  },
  {
    voc: "treasure",
    meaning: "châu báu, của cải",
    image: require("./data/4000B2_1199.jpg"),
    sound: require("./data/4000B2_treasure.mp3"),
  },
  {
    voc: "urge",
    meaning: "thúc giục, nài nỉ",
    image: require("./data/4000B2_1200.jpg"),
    sound: require("./data/4000B2_urge.mp3"),
  },
];

export const vocs: Vocabulary[] = [...new_vocs];
