import { AppTheme } from "@/constants/app-theme";
import { StyleSheet } from "react-native";

export function createHomeStyles(theme: AppTheme, screenWidth: number) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
      alignItems: "center",
      justifyContent: "center",
    },
    header: {
      position: "absolute",
      top: 50,
      right: 20,
      alignItems: "flex-end",
      gap: 8,
      zIndex: 100,
    },
    settingsBtn: {
      padding: 4,
    },
    counter: {
      color: theme.textMuted,
      fontSize: 15,
      fontWeight: "600",
    },
    cardArea: {
      width: screenWidth - 40,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderRadius: 24,
    },
    card: {
      width: screenWidth,
      backgroundColor: theme.card,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 36,
      paddingHorizontal: 20,
      gap: 16,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 12,
    },
    image: {
      width: 280,
      height: 280,
      borderRadius: 16,
      backgroundColor: theme.cardImageBg,
    },
    divider: {
      width: 60,
      height: 2,
      backgroundColor: theme.accent,
      borderRadius: 2,
    },
    word: {
      fontSize: 32,
      fontWeight: "800",
      color: theme.accent,
      textAlign: "center",
      letterSpacing: 1,
      marginBottom: 4,
    },
    pos: {
      fontSize: 16,
      fontWeight: "800",
      color: theme.ipa,
      textAlign: "center",
      letterSpacing: 1,
      marginBottom: 4,
    },
    soundRow: {
      flexDirection: "row",
      width: "80%",
      alignSelf: "center",
      gap: 20,
      marginBottom: 8,
      paddingHorizontal: 8,
    },
    soundRowLeft: {
      justifyContent: "flex-start",
    },
    soundRowCenter: {
      justifyContent: "center",
    },
    soundRowRight: {
      justifyContent: "flex-end",
    },
    soundBtn: {
      padding: 4,
    },
    meaningContainer: {
      alignItems: "center",
      gap: 12,
    },
    meaning: {
      fontSize: 20,
      fontWeight: "500",
      color: theme.meaning,
      textAlign: "center",
    },
    hiddenMeaningPlaceholder: {
      marginTop: 8,
      paddingVertical: 12,
      paddingHorizontal: 24,
      backgroundColor: theme.placeholderBg,
      borderRadius: 20,
    },
    tapHint: {
      color: theme.textMuted,
      fontSize: 14,
      fontStyle: "italic",
    },
    hintRow: {
      position: "absolute",
      bottom: 70,
      flexDirection: "row",
      width: "100%",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    hintLeft: {
      flex: 1,
      color: theme.textMuted,
      fontSize: 14,
      fontWeight: "500",
      textAlign: "left",
      height: 50,
      textAlignVertical: "center",
    },
    hintRight: {
      flex: 1,
      color: theme.textMuted,
      fontSize: 14,
      fontWeight: "500",
      textAlign: "right",
      height: 50,
      textAlignVertical: "center",
    },
    cardHeader: {
      position: "absolute",
      bottom: "auto",
      left: 16,
      zIndex: 10,
    },
    learnButton: {
      padding: 8,
    },
    congratsText: {
      fontSize: 32,
      fontWeight: "bold",
      color: theme.success,
      marginBottom: 8,
    },
    congratsSub: {
      fontSize: 18,
      color: theme.textSecondary,
    },
    floatingButton: {
      position: "absolute",
      top: 50,
      left: 20,
      backgroundColor: theme.accent,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 25,
      flexDirection: "row",
      alignItems: "center",
      zIndex: 100,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 5,
      elevation: 8,
    },
    floatingButtonText: {
      color: theme.floatingBtnText,
      fontWeight: "bold",
      marginLeft: 8,
      fontSize: 14,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      width: "85%",
      maxHeight: "70%",
      backgroundColor: theme.card,
      borderRadius: 24,
      padding: 24,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 20,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: theme.accent,
    },
    modalScroll: {
      paddingBottom: 20,
    },
    categorySection: {
      marginBottom: 20,
    },
    categoryLabel: {
      color: theme.textSecondary,
      fontSize: 16,
      fontWeight: "bold",
      flex: 1,
    },
    setGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    setCard: {
      width: "47%",
      backgroundColor: theme.setCardBg,
      padding: 16,
      borderRadius: 16,
      marginBottom: 16,
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
    },
    activeSetCard: {
      borderColor: theme.activeSetBorder,
      borderWidth: 2,
      borderStyle: "dashed",
    },
    setCardText: {
      color: theme.text,
      fontSize: 16,
      fontWeight: "600",
    },
    activeSetCardText: {
      color: theme.activeSetText,
    },
    setCardSubText: {
      color: theme.textMuted,
      fontSize: 12,
      marginTop: 4,
    },
    lockedCategorySection: {
      opacity: 0.55,
    },
    lockedSetCard: {
      opacity: 0.7,
      backgroundColor: theme.placeholderBg,
    },
    lockedSetCardText: {
      color: theme.textMuted,
    },
    categoryLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
      marginLeft: 4,
      gap: 6,
    },
    lockHint: {
      color: theme.textMuted,
      fontSize: 12,
      marginLeft: 4,
      marginBottom: 8,
      fontStyle: "italic",
    },
  });
}
