import { AppTheme } from "@/constants/app-theme";
import { StyleSheet } from "react-native";

/** Styles cho màn shuffle / review từ vựng (có scope picker: bộ/loại/tất cả). */
export function createReviewStyles(theme: AppTheme, screenWidth: number) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
      alignItems: "center",
    },
    header: {
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 12,
    },
    headerSide: {
      width: 40,
      alignItems: "flex-start",
    },
    headerTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: 18,
      fontWeight: "700",
      color: theme.text,
    },
    poolCount: {
      textAlign: "center",
      color: theme.textMuted,
      fontSize: 14,
      marginBottom: 8,
    },
    scopeRow: {
      flexDirection: "row",
      alignSelf: "center",
      backgroundColor: theme.placeholderBg,
      borderRadius: 999,
      padding: 4,
      marginBottom: 10,
    },
    scopeBtn: {
      paddingVertical: 6,
      paddingHorizontal: 18,
      borderRadius: 999,
    },
    scopeBtnLeft: {},
    scopeBtnRight: {},
    scopeBtnActive: {
      backgroundColor: theme.accent,
    },
    scopeBtnText: {
      color: theme.textSecondary,
      fontSize: 14,
      fontWeight: "600",
    },
    scopeBtnTextActive: {
      color: theme.floatingBtnText,
    },
    soundModeRow: {
      flexDirection: "row",
      alignSelf: "center",
      backgroundColor: theme.placeholderBg,
      borderRadius: 999,
      padding: 4,
      marginBottom: 10,
    },
    soundModeBtn: {
      paddingVertical: 6,
      paddingHorizontal: 16,
      borderRadius: 999,
    },
    soundModeBtnLeft: {},
    soundModeBtnRight: {},
    soundModeBtnActive: {
      backgroundColor: theme.iconTeal,
    },
    soundModeBtnText: {
      color: theme.textSecondary,
      fontSize: 13,
      fontWeight: "600",
    },
    soundModeBtnTextActive: {
      color: theme.floatingBtnText,
    },
    cardSlot: {
      flex: 1,
      width: "100%",
      justifyContent: "center",
      alignItems: "center",
    },
    cardArea: {
      width: screenWidth - 40,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderRadius: 24,
    },
    card: {
      width: screenWidth,
      backgroundColor: theme.card,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 36,
      paddingHorizontal: 20,
      gap: 16,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 12,
    },
    imageWrap: {
      position: "relative",
      width: 336,
      height: 336,
      overflow: "visible",
    },
    image: {
      width: 336,
      height: 336,
      borderRadius: 16,
      backgroundColor: theme.cardImageBg,
    },
    playBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 24,
      backgroundColor: theme.placeholderBg,
    },
    playBtnText: {
      color: theme.textSecondary,
      fontSize: 16,
      fontWeight: "600",
    },
    hint: {
      color: theme.textMuted,
      fontSize: 13,
      fontStyle: "italic",
      textAlign: "center",
    },
    footer: {
      width: "100%",
      paddingHorizontal: 24,
      paddingBottom: 32,
      gap: 12,
      alignItems: "center",
    },
    masteredBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: theme.success,
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderRadius: 28,
      width: "100%",
    },
    masteredBtnText: {
      color: "#ffffff",
      fontSize: 16,
      fontWeight: "700",
    },
    nextBtn: {
      paddingVertical: 8,
    },
    nextBtnText: {
      color: theme.iconTeal,
      fontSize: 15,
      fontWeight: "600",
    },
    emptyWrap: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 32,
      gap: 12,
    },
    emptyTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: theme.accent,
      textAlign: "center",
    },
    emptySub: {
      fontSize: 15,
      color: theme.textMuted,
      textAlign: "center",
      lineHeight: 22,
    },
  });
}
